'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {assetRequest} from '@/components/assets/request';
import {availability,ukToday,type Booking} from '@/lib/fleet-scheduler/model';
import type {LinkedJcbMachine} from '@/lib/integrations/jcb/types';
import {machineKey} from '@/lib/integrations/jcb/types';
import {fleetBrand} from '@/lib/fleet-map/preferences';
import {useFleetStatuses,FleetStatus} from '@/components/assets/fleet-status';
import './style.css';
type Data={bookingMachines:{id:string;machine_number:string}[];machines:LinkedJcbMachine[];bookings:Booking[];checkedAt:string;sources:{provider:string;available:boolean}[];groupError:boolean};
export function FleetScheduler(){
 const [start,setStart]=useState(ukToday),[end,setEnd]=useState(ukToday),[data,setData]=useState<Data|null>(null),[version,setVersion]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [query,setQuery]=useState(''),[brand,setBrand]=useState('all'),[category,setCategory]=useState('Plant'),[state,setState]=useState('all'),[page,setPage]=useState(0),[selected,setSelected]=useState<{key:string;id:string}|null>(null);
 const statuses=useFleetStatuses(version);
 useEffect(()=>{const c=new AbortController();setLoading(true);setData(null);setError('');void assetRequest<Data>(`/api/fleet/scheduler?${new URLSearchParams({start,end})}`,c.signal).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[start,end,version]);
 const rows=useMemo(()=>{const now=Date.now();return (data?.machines??[]).filter(m=>(brand==='all'||fleetBrand(m)===brand)&&(category==='all'||(m.assetCategory??'Unclassified')===category)&&`${m.relay?.machine_number??''} ${m.equipmentId} ${m.model}`.toLowerCase().includes(query.trim().toLowerCase())).map(m=>({m,a:availability(m,data?.bookings??[],start,end,now)}));},[data,brand,category,query,start,end]);
 const visible=rows.filter(r=>state==='all'||r.a.state===state),shownPage=Math.min(page,Math.max(0,Math.ceil(visible.length/30)-1));
 const counts=rows.reduce<Record<string,number>>((all,r)=>({...all,[r.a.state]:(all[r.a.state]??0)+1}),{});
 async function cancel(id:string){setBusy(true);setError('');try{await assetRequest('/api/fleet/scheduler',undefined,{action:'cancel',id});setMessage('Reservation cancelled.');setVersion(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Unable to cancel.');}finally{setBusy(false);}}
 return <section className="scheduler"><header><div><h1>Fleet scheduler</h1><p>Plan jobs using yard availability and dated tracking reports.</p></div><Link href="/fleet/map">Combined fleet map →</Link><button disabled={loading||busy} onClick={()=>setVersion(v=>v+1)}>Refresh</button></header>
 <div className="schedule-filters"><label>From<input type="date" value={start} onChange={e=>{setStart(e.target.value);setSelected(null);setPage(0);}}/></label><label>To (inclusive)<input type="date" value={end} min={start} onChange={e=>{setEnd(e.target.value);setSelected(null);setPage(0);}}/></label><label>Category<select value={category} onChange={e=>{setCategory(e.target.value);setPage(0);}}><option value="all">All assets</option>{[...new Set(['Plant',...(data?.machines??[]).map(m=>m.assetCategory??'Unclassified')])].sort().map(c=><option key={c}>{c}</option>)}</select></label><label>Brand<select value={brand} onChange={e=>{setBrand(e.target.value);setPage(0);}}><option value="all">All brands</option>{[...new Set((data?.machines??[]).map(fleetBrand))].sort().map(b=><option key={b}>{b}</option>)}</select></label><label>Find machine<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label></div>
 <p>Availability is based on the latest GPS report and the Garboldisham yard boundary. It is not a mechanical release check. Future reservations are plans; confirm return and condition before dispatch.</p>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{loading&&<p role="status">Loading availability…</p>}
 {data&&<>{data.sources.some(s=>!s.available)&&<p role="alert">Some tracking sources are unavailable. Their machines may be missing from this view.</p>}{data.groupError&&<p role="alert">Asset categories could not be loaded. Refresh before planning.</p>}
 <div className="schedule-counts">{[['all','All'],['available','In yard / available'],['reserved','Reserved'],['away','On hire / away'],['transit','In transit'],['unknown','Location needs attention'],['unlinked','Needs linking']].map(([key,label])=><button key={key} aria-pressed={state===key} onClick={()=>{setState(key);setPage(0);}}><strong>{key==='all'?rows.length:counts[key]??0}</strong>{label}</button>)}</div>
 <section aria-label="Reservation diary"><h2>Reservations in this period</h2>{!data.bookings.length?<p>No reservations for these dates.</p>:data.bookings.map(b=><div className="schedule-booking" key={b.id}><strong>{data.bookingMachines.find(m=>m.id===b.machine_id)?.machine_number??'Machine not in current fleet'} · Job {b.job_reference}</strong><p>{b.site} · {b.starts_on} → {b.ends_on} (planned end)</p><button disabled={busy} onClick={()=>void cancel(b.id)}>Cancel reservation</button></div>)}</section>
 <p>{visible.length} machines · checked {new Date(data.checkedAt).toLocaleString('en-GB',{timeZone:'Europe/London'})}</p><div className="schedule-machines">{visible.slice(shownPage*30,shownPage*30+30).map(({m,a})=><article key={machineKey(m)}><h2>{m.relay?.machine_number||m.equipmentId} · {fleetBrand(m)}</h2><p>{m.model}</p><strong className={`schedule-state schedule-${a.state}`}>{a.label}</strong><p>{a.at?`GPS: ${new Date(a.at).toLocaleString('en-GB',{timeZone:'Europe/London'})}`:'No dated position'}{a.state==='reserved'?` · ${a.inYard?'Currently in yard':'Currently away from yard'}`:''}</p><FleetStatus status={statuses[machineKey(m)]}/>{a.transit&&<p>Ignition off with reported travel · inferred {new Date(a.transit.at).toLocaleString('en-GB',{timeZone:'Europe/London'})}</p>}
 {a.reserved.map(b=><div className="schedule-booking" key={b.id}><strong>Job {b.job_reference} · {b.site}</strong><p>{b.starts_on} → {b.ends_on}</p>{b.notes&&<p>{b.notes}</p>}<button disabled={busy} onClick={()=>void cancel(b.id)}>Cancel reservation</button></div>)}
 {m.relay&&<div className="schedule-actions"><Link href={`/assets/${m.relay.id}`}>Machine record</Link><button disabled={busy||a.reserved.length>0||start<ukToday()} onClick={()=>setSelected({key:machineKey(m),id:crypto.randomUUID()})}>Plan reservation</button></div>}
 {selected?.key===machineKey(m)&&<form onSubmit={async e=>{e.preventDefault();if(!m.relay)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await assetRequest('/api/fleet/scheduler',undefined,{id:selected.id,machineId:m.relay.id,start,end,job:f.get('job'),site:f.get('site'),notes:f.get('notes')});setSelected(null);setMessage('Reservation saved.');setVersion(v=>v+1);}catch(err){setError(err instanceof Error?err.message:'Unable to reserve machine.');}finally{setBusy(false);}}}><h3>Reserve {m.relay?.machine_number}</h3><p>{start} → {end}. {a.state!=='available'?'Machine is not confirmed available in the yard now. This records a future plan only.':''}</p><label>Job reference<input name="job" required maxLength={100} disabled={busy}/></label><label>Site / customer<input name="site" required maxLength={200} disabled={busy}/></label><label>Notes<textarea name="notes" maxLength={1000} disabled={busy}/></label><button disabled={busy} type="submit">Save reservation</button><button disabled={busy} type="button" onClick={()=>setSelected(null)}>Close</button></form>}
 </article>)}</div>{!visible.length&&<p>No machines match these filters.</p>}{visible.length>30&&<nav aria-label="Scheduler pages"><button disabled={shownPage===0} onClick={()=>setPage(shownPage-1)}>Previous</button><span>Page {shownPage+1} of {Math.ceil(visible.length/30)}</span><button disabled={(shownPage+1)*30>=visible.length} onClick={()=>setPage(shownPage+1)}>Next</button></nav>}</>}
 </section>;
}
