'use client';
import {useEffect,useState} from 'react';
import {assetRequest} from '@/components/assets/request';

type Job={jobNumber:string;fleetNumber:string|null;status:number;jobDate:string|null};
type Result={enabled:boolean;admin:boolean;machine:{id:string;fleetNumber:string};mapping:{sourceReference:string;reviewedAt:string}|null;jobs:Job[];hasMore:boolean;checkedAt?:string;dataFreshness?:string;database?:string};
const when=(value?:string|null)=>value?new Date(value).toLocaleString('en-GB',{timeZone:'Europe/London'}):'Not recorded';

export function InspHireJobsPanel({machineId,fleetNumber,compact=false}:{machineId:string;fleetNumber:string;compact?:boolean}){
 const [data,setData]=useState<Result|null>(null),[error,setError]=useState(''),[editing,setEditing]=useState(false),[reference,setReference]=useState(fleetNumber),[saving,setSaving]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{const controller=new AbortController();setError('');void assetRequest<Result>(`/api/integrations/insphire-test/assets/${encodeURIComponent(machineId)}`,controller.signal).then(result=>{if(!controller.signal.aborted){setData(result);setReference(result.mapping?.sourceReference??fleetNumber);}}).catch(cause=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'InspHire jobs are unavailable.');});return()=>controller.abort();},[machineId,fleetNumber,version]);
 async function save(value:string){setSaving(true);setError('');try{await assetRequest(`/api/integrations/insphire-test/assets/${encodeURIComponent(machineId)}`,undefined,{sourceReference:value});setEditing(false);setVersion(current=>current+1);}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save the InspHire mapping.');}finally{setSaving(false);}}
 if(error&&!data)return <section className={`insphire-jobs${compact?' insphire-jobs-compact':''}`}><strong>InspHire Jobs</strong><p role="alert">{error}</p></section>;
 if(!data)return <section className={`insphire-jobs${compact?' insphire-jobs-compact':''}`} role="status"><strong>InspHire Jobs</strong><p>Checking reviewed asset link…</p></section>;
 return <section className={`insphire-jobs${compact?' insphire-jobs-compact':''}`} aria-label="InspHire jobs"><header><div><span>Historical Test Data</span><h3>InspHire Jobs</h3></div>{data.mapping&&<b>Read Only</b>}</header>
  {!data.mapping?<><p>No reviewed InspHire asset reference is linked to this machine.</p>{data.admin&&<button className="jcb-button" onClick={()=>setEditing(true)}>Link InspHire Reference</button>}</>:<><p><strong>{data.mapping.sourceReference}</strong> · reviewed {when(data.mapping.reviewedAt)}</p>{!data.enabled?<p className="insphire-jobs-note">Connector disabled in this environment.</p>:<><p className="insphire-jobs-note">{data.dataFreshness} · checked {when(data.checkedAt)}</p>{data.jobs.length?<div className="insphire-job-list">{data.jobs.map(job=><article key={job.jobNumber}><strong>{job.jobNumber}</strong><span>Source Status {job.status}</span><small>{job.jobDate??'Job date unavailable'} · {job.fleetNumber??'No asset reference'}</small></article>)}</div>:<p>No matching jobs in the historical test copy.</p>}{data.hasMore&&<p>More than 25 matching jobs exist. Use the diagnostic lookup to narrow the result.</p>}</>}{data.admin&&<div className="insphire-jobs-actions"><button className="jcb-button" onClick={()=>setEditing(true)}>Change Link</button><button className="jcb-button" disabled={saving} onClick={()=>void save('')}>Remove Link</button></div>}</>}
  {editing&&data.admin&&<form onSubmit={event=>{event.preventDefault();void save(reference.trim());}}><label>Exact InspHire Asset Reference<input autoFocus value={reference} onChange={event=>setReference(event.target.value)} maxLength={32}/></label><p>This reviewed reference controls which historical InspHire jobs are shown. It does not change either system.</p><div><button className="jcb-button jcb-primary" disabled={saving||!reference.trim()}>{saving?'Saving…':'Save Reviewed Link'}</button><button className="jcb-button" type="button" disabled={saving} onClick={()=>setEditing(false)}>Cancel</button></div></form>}
  {error&&<p role="alert">{error}</p>}
 </section>;
}
