import {describe,it,expect} from 'vitest';
import {mayAct,roamAvailability,workflowAction,type HireAssessment} from '@/lib/fleet-workflow/model';
import {availability} from '@/lib/fleet-scheduler/model';
import type {LinkedJcbMachine} from '@/lib/integrations/jcb/types';
const row:HireAssessment={machine_id:'10000000-0000-4000-8000-000000000001',machine_number:'DEMO',status:'available',available:true,version:1,blockers:[]};
describe('hire clearance',()=>{
 it('restricts overrides to admins and explicitly designated hire staff',()=>{expect(mayAct({admin:false,workshop:true,parts:true,hire:false},'override')).toBe(false);expect(mayAct({admin:false,workshop:false,parts:false,hire:true},'override')).toBe(true);expect(mayAct({admin:true,workshop:false,parts:false,hire:false},'override')).toBe(true)});
 it('does not export private notes or invent availability from inconsistent state',()=>{const result=roamAvailability({...row,status:'on_hold',state:{location:'yard',arrived_at:null,next_service_date:null,next_service_hours:null,last_service_at:null,departure_status:null,override_reason:'Private reason'}});expect(result.available).toBe(false);expect(JSON.stringify(result)).not.toContain('Private reason');expect(roamAvailability({...row,status:'available_override'}).override).toBe(true)});
 it('requires a meaningful reason and rejects invalid payloads',()=>{expect(workflowAction.safeParse({id:row.machine_id,machineId:row.machine_id,version:1,action:'override',reason:'yes'}).success).toBe(false);expect(workflowAction.safeParse({id:row.machine_id,machineId:row.machine_id,version:1,action:'override',reason:'Hire manager decision',payload:{next_service_hours:-1}}).success).toBe(false)});
 it('keeps yard presence separate from clearance and respects bookings',()=>{const now=Date.parse('2026-09-30T12:00:00Z');const m={pin:'demo',equipmentId:'demo',model:'Demo',match:'exact',relay:{id:row.machine_id,machine_number:'DEMO',make:'Demo',model:null,serial_number:null},position:{latitude:52.3925,longitude:.955,at:new Date(now).toISOString()}} as LinkedJcbMachine;const state=(r:HireAssessment|null)=>availability(m,[],'2026-09-30','2026-09-30',now,r).state;expect(state(null)).toBe('hold');expect(state({...row,status:'on_hold',available:false})).toBe('hold');expect(state(row)).toBe('available');expect(state({...row,status:'available_override'})).toBe('override');expect(availability(m,[{id:'test',machine_id:row.machine_id,starts_on:'2026-09-30',ends_on:'2026-09-30',job_reference:'Demo',site:'Demo',notes:null,status:'reserved',created_by:'test',created_at:''}],'2026-09-30','2026-09-30',now,row).state).toBe('reserved')});
});
