import {expect,it} from 'vitest';
import {answerTelematics,isTelematicsQuestion} from '@/lib/relay-ai-telematics';
import {plantBoardData,plantPositions} from '@/lib/plant-wallboard/model';
import type {BoardMachine} from '@/lib/plant-wallboard/positions';
import type {YardEvent} from '@/lib/yard-report';
const now=Date.parse('2026-09-28T12:00:00Z');
const machine:BoardMachine={pin:'x',equipmentId:'12345',model:'Excavator',source:'jcb',position:{latitude:52,longitude:1,at:'2026-09-20T12:00:00Z'},assetCategory:'Plant',match:'exact',relay:{id:'a',machine_number:'12345',make:'JCB',model:'Excavator',serial_number:null}};
const missing={...machine,pin:'y',position:null,relay:{...machine.relay!,id:'b',machine_number:'26304'}};
const machines=[machine,missing],allowed=new Set(['a','b']);
const events:YardEvent[]=[{id:'one',machine_id:'a',kind:'yard_arrival',provider:'jcb',occurred_at:'2026-09-27T22:00:00Z',machine:{machine_number:'12345',make:'JCB',model:'Excavator'}},{id:'two',machine_id:'a',kind:'yard_departure',provider:'jcb',occurred_at:'2026-09-28T10:00:00Z',machine:{machine_number:'12345',make:'JCB',model:'Excavator'}}];
const snapshot={data:{...plantBoardData(machines,allowed,events,now),warning:null},positions:plantPositions(machines,allowed,now),machines,events,now};
it.each(['Where is machine 12345?','Which trackers need attention?','Give me a director plant summary','Show today’s yard movements'])('routes tracking question %s',q=>expect(isTelematicsQuestion(q)).toBe(true));
it.each(['What is the oil filter for 12345?','List Shred Station fleet request counts','Who handles the most jobs?'])('preserves existing nontracking routing %s',q=>expect(isTelematicsQuestion(q)).toBe(false));
it('answers exact locations with last-known age and source evidence',()=>{const a=answerTelematics('Where is machine 12345?',snapshot);expect(a.text).toContain('outside Garboldisham');expect(a.text).toContain('old or undated');expect(a.text).toContain('52.000000');expect(a.sourceNote).toContain('28/09/2026');expect(a.directions?.url).toContain('destination=52,1');});
it('does not infer hardware failure from missing or old GPS',()=>{expect(answerTelematics('Where is machine 26304?',snapshot).text).toContain('cannot establish a hardware failure');expect(answerTelematics('Which trackers need attention?',snapshot).text).toContain('26304');});
it('matches wallboard totals for director summaries',()=>{const a=answerTelematics('Director plant summary',snapshot);expect(a.text).toContain('2 tracked plant: 0 recently reported in the yard, 0 recently reported outside and 2 needing confirmation');});
it('uses today’s events and preserves history caveats',()=>{const a=answerTelematics('Show today’s yard movements',snapshot);expect(a.text).toContain('1 departures and 0 returns');expect(a.text).toContain('earlier periods may be incomplete');});
it('does not invent untracked identities or unsupported historical ranges',()=>{expect(answerTelematics('Where is machine 99999?',snapshot).text).toContain('No active, owned');expect(answerTelematics('yard movements yesterday',snapshot).text).toContain('another date range');});
it('keeps tracking changes read-only and discloses source delays',()=>{expect(answerTelematics('Assign tracker 12345',snapshot).text).toContain('cannot assign');expect(answerTelematics('plant summary',{...snapshot,data:{...snapshot.data,warning:'Collection delayed'}}).sourceNote).toContain('Collection delayed');});

it('does not route an admin to a conflicting location',()=>{const uncertain={...snapshot,positions:snapshot.positions.map(p=>({...p,status:'unknown' as const}))};expect(answerTelematics('Where is 12345?',uncertain).directions).toBeNull();});
