import {beforeEach,expect,it,vi} from 'vitest';
import {NextRequest} from 'next/server';
import {trackingSnapshot} from '@/lib/integrations/roam/tracking';
import type {LinkedJcbMachine} from '@/lib/integrations/jcb/types';
const m=vi.hoisted(()=>({from:vi.fn(),jcb:vi.fn(),track:vi.fn(),create:vi.fn(),tables:{} as Record<string,unknown[]>}));
vi.mock('server-only',()=>({}));
vi.mock('@supabase/supabase-js',()=>({createClient:m.create}));
vi.mock('@/lib/integrations/jcb/client',()=>({getJcbFleet:m.jcb}));
vi.mock('@/lib/integrations/trackunit/client',()=>({getTrackunitFleet:m.track}));
vi.mock('@/lib/integrations/jcb/normalize',()=>({linkMachines:(x:unknown)=>x}));
vi.mock('@/lib/integrations/trackunit/normalize',()=>({linkTrackunitMachines:(x:unknown)=>x}));
import {GET} from '@/app/api/partners/roam/tracking/route';
const machine=(id='1'):LinkedJcbMachine=>({pin:'PIN'+id,equipmentId:id,model:'test',position:{latitude:52,longitude:1,at:'2026-09-24T10:00:00Z'},relay:{id,machine_number:id,make:'JCB',model:'test',serial_number:'PIN'+id},match:'exact'});
const source={provider:'jcb' as const,available:true,checked_at:'2026-09-24T11:00:00Z'};
const req=(token='tracking-secret')=>new NextRequest('https://relay.test/api/partners/roam/tracking',{headers:{authorization:'Bearer '+token}});
beforeEach(()=>{vi.clearAllMocks();vi.stubEnv('ROAM_TRACKING_FEED_TOKEN','tracking-secret');vi.stubEnv('ROAM_TRACKING_ENABLED','true');vi.stubEnv('ROAM_TRACKING_FEED_TOKEN_PREVIOUS','');vi.stubEnv('NEXT_PUBLIC_SUPABASE_URL','https://example.supabase.co');vi.stubEnv('JCB_HEALTH_DATABASE_KEY','test');vi.stubEnv('JCB_LIVELINK_ENABLED','true');vi.stubEnv('TRACKUNIT_ENABLED','true');m.tables={machines:[{...machine().relay,lifecycle_status:'active'}],customer_fleet_machines:[],jcb_livelink_mappings:[],trackunit_mappings:[]};m.create.mockReturnValue({from:m.from});m.from.mockImplementation((table:string)=>{const q={select:()=>q,order:()=>q,range:async()=>({data:m.tables[table],error:null})};return q});m.jcb.mockResolvedValue({machines:[machine()],checkedAt:source.checked_at});m.track.mockResolvedValue({machines:[],checkedAt:source.checked_at});});
it('rejects unauthenticated calls before database or providers',async()=>{expect((await GET(req('bad'))).status).toBe(401);expect(m.create).not.toHaveBeenCalled();expect(m.jcb).not.toHaveBeenCalled()});
it('never falls back to the existing fleet feed credential',async()=>{vi.stubEnv('ROAM_TRACKING_FEED_TOKEN',undefined);vi.stubEnv('RICO_FLEET_FEED_TOKEN','rico');expect((await GET(req('rico'))).status).toBe(401)});
it('supports dedicated previous-key rotation',async()=>{vi.stubEnv('ROAM_TRACKING_FEED_TOKEN_PREVIOUS','previous');expect((await GET(req('previous'))).status).toBe(200)});
it('exports tracked active MLP rows with private caching',async()=>{const r=await GET(req());expect(r.headers.get('cache-control')).toContain('no-store');expect((await r.json()).assets[0].relay_id).toBe('1')});
it('excludes customer-owned assets',async()=>{m.tables.customer_fleet_machines=[{machine_id:'1',fleet_id:'customer'}];expect((await(await GET(req())).json()).assets).toEqual([])});
it('excludes sold and disposed registry rows',async()=>{for(const lifecycle_status of ['sold','disposed']){m.tables.machines=[{...machine().relay,lifecycle_status}];expect((await(await GET(req())).json()).assets).toEqual([])}});
it('fails closed when ownership cannot be checked',async()=>{m.from.mockImplementation(()=>{throw Error('private database error')});const r=await GET(req());expect(r.status).toBe(503);expect(JSON.stringify(await r.json())).not.toContain('private database error');expect(m.jcb).not.toHaveBeenCalled()});
it('marks partial source failure explicitly, both failures give 503',async()=>{m.track.mockRejectedValue(Error('secret'));const r=await GET(req());const d=await r.json();expect(r.status).toBe(200);expect(d.complete).toBe(false);expect(d.sources[1].available).toBe(false);m.jcb.mockRejectedValue(Error());expect((await GET(req())).status).toBe(503)});
it('excludes unverified identities and invalid positions',()=>{const rows=[{...machine(),relay:null},{...machine('2'),match:'ambiguous' as const},{...machine('3'),position:null},{...machine('4'),position:{latitude:999,longitude:1,at:null}}];expect(trackingSnapshot([{source,machines:rows}],new Set(['1','2','3','4'])).assets).toEqual([])});
it('deduplicates linked assets using newest provider position',()=>{const a=machine();const b={...a,position:{...a.position!,at:'2026-09-24T11:00:00Z'}};const d=trackingSnapshot([{source,machines:[a]},{source:{...source,provider:'trackunit'},machines:[b]}],new Set(['1']));expect(d.assets).toHaveLength(1);expect(d.assets[0].provider).toBe('trackunit')});
it('labels unknown, future and stale report times honestly',()=>{for(const [at,status] of [[null,'unknown'],['2026-09-25T00:00:00Z','check_timestamp'],['2026-09-20T00:00:00Z','stale']]){const a={...machine(),position:{latitude:52,longitude:1,at}};expect(trackingSnapshot([{source,machines:[a]}],new Set(['1']),Date.parse('2026-09-24T12:00:00Z')).assets[0].position_status).toBe(status)}});
