import {beforeEach,expect,it,vi} from 'vitest';
import {NextRequest,NextResponse} from 'next/server';
const m=vi.hoisted(()=>({auth:vi.fn(),fleet:vi.fn(),details:vi.fn(),jcbAuth:vi.fn(),jcbFleet:vi.fn()}));
vi.mock('server-only',()=>({}));vi.mock('next/cache',()=>({unstable_cache:(fn:unknown)=>fn}));
vi.mock('@/lib/integrations/trackunit/server',()=>({authorizeTrackunit:m.auth,getLinkedTrackunitFleet:m.fleet,trackunitError:(e:{message:string;status?:number})=>NextResponse.json({error:e.message},{status:e.status??503})}));
vi.mock('@/lib/integrations/trackunit/client',()=>({getTrackunitDetails:m.details}));
vi.mock('@/lib/integrations/jcb/server',()=>({authorizeJcb:m.jcbAuth,getLinkedFleet:m.jcbFleet,jcbJson:(d:unknown,status=200)=>NextResponse.json(d,{status}),jcbError:(e:{message:string;status?:number})=>NextResponse.json({error:e.message},{status:e.status??503})}));
import {GET as detail} from '@/app/api/integrations/trackunit/machine/route';
import {GET as context} from '@/app/api/integrations/trackunit/context/route';
import {GET as combined} from '@/app/api/integrations/combined/fleet/route';
const machine={source:'trackunit',pin:'MAN1',equipmentId:'1',model:'MT',position:null,relay:{machine_number:'1'},match:'exact'};
const req=(query='pin=MAN1')=>new NextRequest(`https://relay.test/api?${query}`);
beforeEach(()=>{vi.clearAllMocks();m.auth.mockResolvedValue({admin:false});m.jcbAuth.mockResolvedValue({admin:true});m.fleet.mockResolvedValue({machines:[machine],checkedAt:'2026-09-24T10:00:00Z'});m.jcbFleet.mockResolvedValue({machines:[{...machine,source:'jcb'}]});m.details.mockResolvedValue({faults:[{code:'SPN 1 / FMI 2',description:'Reported problem',severity:'Not supplied',at:'2026-09-24T10:00:00Z'}],telemetry:[{name:'Fuel Level',value:'5',uoM:'%',time:'2026-09-24T10:00:00Z'}],checkedAt:'2026-09-24T10:00:00Z',faultError:false,telemetryError:false});});
it('fitters receive dated faults but no admin telemetry',async()=>{const d=await(await detail(req())).json();expect(d.faults).toHaveLength(1);expect(d).not.toHaveProperty('telemetry');expect(d.machine).not.toHaveProperty('fuel');});
it('admins receive normalised and original telemetry',async()=>{m.auth.mockResolvedValue({admin:true});const d=await(await detail(req())).json();expect(d.machine.fuel.value).toBe(5);expect(d.telemetry).toHaveLength(1);});
it('unknown machines do not trigger telemetry requests',async()=>{expect((await detail(req('pin=UNKNOWN'))).status).toBe(404);expect(m.details).not.toHaveBeenCalled();});
it('request context requires a verified machine link',async()=>{m.fleet.mockResolvedValue({machines:[{...machine,relay:null}]});expect((await context(req())).status).toBe(409);});
it('fault-linked requests carry the selected code and date',async()=>{const d=await(await context(req('pin=MAN1&fault=SPN+1+%2F+FMI+2'))).json();expect(d.machineReference).toBe('1');expect(d.text).toContain('SPN 1 / FMI 2');expect(d.text).toContain('2026-09-24T10:00:00Z');});
it('missing fault data never creates a misleading fault context',async()=>{m.details.mockResolvedValue({faults:[],faultError:true});expect((await context(req('pin=MAN1&fault=SPN+1'))).status).toBe(503);});
it('combined fleet requires admin authorization for each provider',async()=>{await combined(req());expect(m.auth).toHaveBeenCalledWith(expect.anything(),true);expect(m.jcbAuth).toHaveBeenCalledWith(expect.anything(),true);m.auth.mockRejectedValue({status:403,message:'Denied'});expect((await combined(req())).status).toBe(403);});
it('combined fleet exposes provider outages alongside the remaining fleet',async()=>{m.jcbFleet.mockRejectedValue(new Error('provider outage'));const r=await combined(req());const d=await r.json();expect(r.status).toBe(200);expect(d.machines).toHaveLength(1);expect(d.sources[0].available).toBe(false);expect(d.sources[1].available).toBe(true);});
