'use client';
import {useEffect,useState} from 'react';
import {getSupabaseAccessToken} from '@/lib/supabase';
import type {HireUsage} from '@/lib/integrations/roam/usage';
const date=(at:string)=>new Date(at).toLocaleString('en-GB',{timeZone:'Europe/London'});
export function HireUsageCard({hireId,reference,fleet}:{hireId:string;reference:string;fleet:string}){
 const [usage,setUsage]=useState<HireUsage|null>(null),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();let busy=false;
 async function load(){if(busy)return;busy=true;try{const token=await getSupabaseAccessToken();if(!token)throw Error('Sign in to view contract hours.');const r=await fetch(`/api/integrations/roam/hires/${encodeURIComponent(hireId)}/usage?fleet=${encodeURIComponent(fleet)}`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal});if(!r.ok)throw Error('Contract hours are temporarily unavailable.');const data:HireUsage=await r.json();if(!controller.signal.aborted){setUsage(data);setError('');}}catch(e){if(!controller.signal.aborted){setUsage(null);setError(e instanceof Error?e.message:'Hours unavailable.');}}finally{busy=false;}}
 void load();const timer=setInterval(()=>{if(!document.hidden)void load();},60000);return()=>{controller.abort();clearInterval(timer);};},[hireId,fleet]);
 return <section className="roam-usage" aria-label="Contract hours used"><h3>Contract hours used</h3><p>Hire {reference} · Hours accumulated during this hire</p>{error?<p role="alert">{error}</p>:!usage?<p role="status">Checking delivery and hour readings…</p>:usage.hours===null?<p>{usage.reason||'Usage unavailable.'}</p>:<><strong className="roam-usage-total">{usage.hours.toFixed(2)} hours</strong><p>{usage.source==='driver'?'Driver-recorded meter difference':`Telematics-calculated usage · ${usage.provider} · estimated delivery baseline`}</p><dl className="roam-info"><div><dt>ROAM delivery</dt><dd>{date(usage.deliveryAt!)} UK</dd></div><div><dt>Starting counter</dt><dd>{usage.start!.value.toFixed(3)} h · {date(usage.start!.at)} UK</dd></div><div><dt>Latest counter</dt><dd>{usage.end!.value.toFixed(3)} h · {date(usage.end!.at)} UK</dd></div></dl>{usage.stale&&<p className="roam-error">Latest reading is over 30 minutes old. Usage is only calculated to the timestamp shown.</p>}{usage.source==='telematics'&&<p>Uses the same tracker counter at both ends, with a reading no more than 15 minutes before delivery. Tracker hours can include ignition-on idle time and may differ from the machine hour meter.</p>}<p>Hire usage only. Contract allowance, excess hours and charges are not calculated.</p></>}</section>;
}
