'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {getSupabaseAccessToken} from '@/lib/supabase';
import type {HourReading} from '@/lib/integrations/roam/hours';
import './style.css';
export function AssetHours({machineId}:{machineId?:string}){
 const [rows,setRows]=useState<HourReading[]>([]),[error,setError]=useState(''),[last,setLast]=useState(''),[busy,setBusy]=useState(false);
 const endpoint='/api/integrations/roam/hours'+(machineId?'?machineId='+encodeURIComponent(machineId):'');
 const request=useCallback(async(method='GET',csv=false)=>{const token=await getSupabaseAccessToken();if(!token)throw Error('Sign in to view hour history.');const r=await fetch(endpoint+(csv?(endpoint.includes('?')?'&':'?')+'format=csv':''),{method,headers:{Authorization:`Bearer ${token}`}});if(!r.ok){const e=await r.json();throw Error(e.error||'Hour history unavailable.')}return r},[endpoint]);
 const load=useCallback(async()=>{try{const r=await request(),data=await r.json();setRows(data.items);setLast(data.last_success||'');}catch(e){setError(e instanceof Error?e.message:'Unable to load readings.')}},[request]);
 useEffect(()=>{void load();const timer=setInterval(()=>{if(!document.hidden)void load()},60000);return()=>clearInterval(timer)},[load]);
 async function sync(){setBusy(true);setError('');try{await request('POST');await load()}catch(e){setError(e instanceof Error?e.message:'Sync failed.')}finally{setBusy(false)}}
 async function download(){try{const r=await request('GET',true),url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='AssetCare+-asset-hours.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Export failed.')}}
 return <section className="roam-hires"><header><h1>Asset hour readings</h1><Link href="/fleet/map">Fleet map</Link>{machineId&&<Link href="/fleet/hours">All assets</Link>}<button disabled={busy} onClick={()=>void sync()}>{busy?'Syncing…':'Sync ROAM now'}</button><button onClick={()=>void download()}>Export CSV</button></header><p>Drop-off and collection meter readings, including completed hires. Automatic sync every five minutes.</p><p>InspHire contracts are not connected yet. Contract allowances and excess hours are not calculated. Usage is the difference between paired meter readings, not elapsed hire time. Exports contain one row per reading; hire usage repeats on its paired rows.</p><p role="status">{last?'Last successful sync: '+new Date(last).toLocaleString():'Awaiting first successful sync.'}</p>{error&&<p role="alert">{error}</p>}{!rows.length&&<p>No recorded hours for this view yet. Earlier movements without meter readings are not estimated.</p>}<div style={{overflowX:'auto'}}><table><thead><tr>{['Asset','Customer / hire','Movement','Recorded','Meter hours','Hire usage','Contract'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link href={'/assets/'+r.relay_asset_id}>{r.fleet_number}</Link></td><td>{r.customer}<br/>{r.hire_reference||'Unlinked collection'}</td><td>{r.movement==='drop_off'?'Drop-off':'Collection'}<br/>{r.driver}</td><td>{new Date(r.recorded_at).toLocaleString()}</td><td>{r.meter_hours}</td><td>{r.used_hours===null?r.usage_status.replaceAll('_',' '):r.used_hours+' hours'}</td><td>Awaiting InspHire</td></tr>)}</tbody></table></div></section>;
}
