'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {assetRequest} from '@/components/assets/request';
import type {StaffData} from '@/lib/staff/model';
import {drivingLeague,mph,type DrivingSort} from '@/lib/staff/driving';
import './style.css';
const when=(at:string)=>new Date(at).toLocaleString('en-GB',{timeZone:'Europe/London',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
export function DrivingLeague(){
 const [data,setData]=useState<StaffData|null>(null),[error,setError]=useState(''),[department,setDepartment]=useState(''),[query,setQuery]=useState(''),[alertsOnly,setAlertsOnly]=useState(false),[sort,setSort]=useState<DrivingSort>('alerts'),[refresh,setRefresh]=useState(0),[loading,setLoading]=useState(true);
 useEffect(()=>{const c=new AbortController();async function load(){try{const result=await assetRequest<StaffData>('/api/staff',c.signal);if(!c.signal.aborted){setData(result);setError('');}}catch(e){if(!c.signal.aborted){setData(null);setError(e instanceof Error?e.message:'Driving data unavailable');}}finally{if(!c.signal.aborted)setLoading(false);}}void load();const timer=setInterval(()=>void load(),60000);return()=>{c.abort();clearInterval(timer);};},[refresh]);
 const rows=useMemo(()=>drivingLeague(data?.rows??[],department,query,alertsOnly,sort),[data,department,query,alertsOnly,sort]);
 const available=rows.filter(r=>r.daily.available),alertCount=available.reduce((sum,r)=>sum+r.daily.speedingCount,0);
 return <section className="staff-page driving-page"><header><div><h1>Driving league</h1><p>Assigned staff vehicles · speeding alerts today, midnight to now (UK time).</p></div><Link className="staff-link" href="/staff">← Staff</Link><button disabled={loading} onClick={()=>{setLoading(true);setRefresh(n=>n+1);}}>Refresh</button></header>
 <p className="staff-note">Admin only · Ranked by provider-reported speeding alerts, not confirmed offences or driver identity. The vehicle’s assigned name may differ from the person driving. Review the event evidence before taking action.</p>
 {error&&<p role="alert">{error}</p>}{loading&&!data&&<p>Loading driving league…</p>}
 {data&&<><p>Updated {when(data.checkedAt)} · saved feed refreshes every minute.{data.rows[0]?.daily.day&&` Reporting date: ${data.rows[0].daily.day}.`}</p>{data.warning&&<p role="alert">{data.warning}</p>}
 <div className="staff-filters"><label>Department<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">All departments</option>{[...new Set(data.rows.map(r=>r.department))].sort().map(d=><option key={d}>{d}</option>)}</select></label><label>Find name / registration<input placeholder="Search staff or vehicle" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value as DrivingSort)}><option value="alerts">Most speeding alerts</option><option value="excess">Largest reported excess</option><option value="speed">Highest event speed</option><option value="name">Name / registration</option></select></label></div>
 <nav aria-label="Department shortcuts">{['','Transport','Plant Office','Workshop'].filter(d=>!d||data.rows.some(r=>r.department===d)).map(d=><button key={d} aria-pressed={department===d} onClick={()=>setDepartment(d)}>{d||'All departments'}</button>)}</nav>
 <label className="driving-checkbox"><input type="checkbox" checked={alertsOnly} onChange={e=>setAlertsOnly(e.target.checked)}/> Only vehicles with recorded alerts</label>
 <div className="staff-counts"><article><strong>{alertCount}</strong><span>Speeding alerts in this filter</span></article><article><strong>{available.filter(r=>r.daily.speedingCount>0).length}</strong><span>Vehicles with alerts</span></article><article><strong>{rows.length}</strong><span>Assigned vehicles shown{available.length<rows.length?` · ${rows.length-available.length} unavailable`:''}</span></article></div>
 <p>Rank is by alert count within your filter; ties share a rank. This is not adjusted for distance or time driven. Zero alerts does not confirm compliant driving or complete tracker coverage.</p>
 <div className="staff-table"><table><caption className="driving-caption">{department||'All departments'} · Today’s driving league</caption><thead><tr><th>Rank</th><th>Staff / assigned vehicle</th><th>Department</th><th>Speeding alerts</th><th>Highest event speed</th><th>Largest excess</th><th>Event evidence</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.rank??'—'}</td><th scope="row">{r.label}</th><td>{r.department}</td><td>{!r.daily.available?'Unavailable':r.daily.speedingCount?<span className="driving-alert">{r.daily.speedingCount} · Review</span>:'No alerts recorded'}</td><td>{r.daily.available?mph(r.daily.peakSpeedKph):'Unavailable'}</td><td>{r.daily.available?mph(r.daily.maxExcessKph):'Unavailable'}<small>Against provider limit</small></td><td>{r.daily.available&&r.daily.drivingAlerts.length>0?<details><summary>View {r.daily.speedingCount>20?'latest 20':r.daily.speedingCount} alerts</summary><ol className="driving-evidence">{r.daily.drivingAlerts.map((e,i)=><li key={`${e.at}:${i}`}><strong>{when(e.at)}</strong><br/>Speed: {mph(e.speedKph)}<br/>Provider limit: {mph(e.limitKph)}</li>)}</ol></details>:r.daily.available?'No evidence received today':'Feed unavailable — retry'}</td></tr>)}</tbody></table></div>{!rows.length&&<p>No vehicles match these filters.</p>}
 <p>Limits are supplied by Asset Care+ and may be configured thresholds rather than the legal limit for that road and vehicle. Counts include all received alerts today; expanded evidence shows the latest 20 per vehicle. Peak values use all received alerts. Harsh braking, cornering and mileage-adjusted scores are not available in this view.</p></>}
 </section>;
}
