'use client';
import {useEffect,useRef} from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import yard from '@/lib/fleet-operations/yard.json';
import type {StaffRow} from '@/lib/staff/model';
export default function StaffMap({rows}:{rows:StaffRow[]}){const el=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),fitted=useRef(false);
 useEffect(()=>{if(!el.current)return;const m=L.map(el.current,{scrollWheelZoom:true}).setView([52.392,.955],15);map.current=m;const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(m);const polygon=L.polygon(yard.geometry.coordinates[0].map(([lon,lat])=>[lat,lon] as [number,number]),{color:'#147b80'}).addTo(m);const observer=new ResizeObserver(()=>m.invalidateSize());observer.observe(el.current);return()=>{observer.disconnect();tiles.remove();polygon.remove();m.remove();map.current=null;};},[]);
 useEffect(()=>{const m=map.current;if(!m)return;const layer=L.layerGroup().addTo(m),bounds=L.latLngBounds([]);for(const row of rows){if(!row.position)continue;const p=row.position;bounds.extend([p.latitude,p.longitude]);const content=document.createElement('div');const title=document.createElement('strong');title.textContent=row.label;const detail=document.createElement('p');detail.textContent=`${row.department} · ${row.status==='in'?'Vehicle in yard':row.status==='out'?'Vehicle outside yard':'Location uncertain'} · ${row.reason} · GPS ${p.at?new Date(p.at).toLocaleString('en-GB'):'unavailable'}`;content.append(title,detail);L.circleMarker([p.latitude,p.longitude],{radius:9,color:'#fff',weight:2,fillOpacity:.9,fillColor:row.status==='in'?'#16805c':row.status==='out'?'#2563eb':'#aa7514'}).bindPopup(content).addTo(layer);}if(!fitted.current&&bounds.isValid()){m.fitBounds(bounds,{padding:[35,35],maxZoom:16});fitted.current=true;}return()=>{layer.remove();};},[rows]);
 return <div ref={el} className="staff-map" aria-label="Staff vehicle locations and yard boundary"/>;}
