"use client";
import {mergeRoamMap} from "@/lib/integrations/roam/map";
import {RoamMapDetails} from "@/components/roam/map-details";
import {useOnHire} from "@/components/roam/use-on-hire";
import {AssetHireLink} from "@/components/roam/asset-hire-link";
import {useSignWatch} from "@/components/sign-watch/use-sign-watch";
import {SignWatchAssetDetails} from "@/components/sign-watch/asset-details";
import {useAssetFlags,FlagMachine,FlaggedList} from '@/components/assets/flags';
import {flagForMachine} from '@/lib/assets/flags';
import {AssetTravel} from '@/components/assets/travel-summary';
import {CollectionHealth} from './collection-health';
import {ShareAssetLocation} from '@/components/assets/share-location';
import {LocationViews} from '@/components/telematics/location-views';
import {MapPreferences} from './map-preferences';
import {defaults,readPreferences,filterFleet,type Preferences} from '@/lib/fleet-map/preferences';
import dynamic from "next/dynamic";
import {useFleetStatuses,FleetStatus,FleetStatusLegend} from "@/components/assets/fleet-status";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {getSupabaseAccessToken} from "@/lib/supabase";
import {machineKey,machineBrand,machineProvider,partsRequestUrl,positionAge,type LinkedJcbMachine,type JcbFault,type RegistryMachine} from "@/lib/integrations/jcb/types";
import {FaultCards} from "@/components/jcb/fault-cards";
import type {Telemetry} from "@/lib/integrations/trackunit/normalize";
import "@/app/livelink/style.css";
import "@/components/jcb/health.css";
import "./style.css";
const FleetMap=dynamic(()=>import("@/components/jcb/livelink-map"),{ssr:false,loading:()=> <p>Loading fleet map…</p>});
type Source={provider:string;available:boolean;count:number;checkedAt:string|null;stale:boolean};
type Fleet={groupError?:boolean;machines:LinkedJcbMachine[];admin:boolean;checkedAt?:string;stale?:boolean;sources?:Source[];assetcareStatus?:{last_attempt_at:string|null;last_ack_at:string|null;last_error:string|null;last_cycle?:{drained:boolean;latestReceivedAt?:string|null;batches:number;records:number}}|null};
type Details={machine:LinkedJcbMachine;faults:JcbFault[];checkedAt:string;faultError?:boolean;telemetryError?:boolean;telemetry?:Telemetry[]};
async function api<T>(provider:string,path:string,signal?:AbortSignal,body?:unknown):Promise<T>{
 const token=await getSupabaseAccessToken();if(!token)throw new Error('Sign in to view fleet tracking.');
 const response=await fetch(`/api/integrations/${provider}/${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal});
 const data=await response.json();if(!response.ok)throw new Error(data.error||'Fleet connection unavailable. Please retry.');return data;
}
const date=(at?:string|null)=>at?new Date(at).toLocaleString('en-GB'):'Time unavailable';
export function TrackingWorkspace({combined=false,request=api,provider="trackunit"}:{combined?:boolean;request?:typeof api;provider?:"trackunit"|"takeuchi"}){
 const [fleet,setFleet]=useState<Fleet|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[version,setVersion]=useState(0);
 const [query,setQuery]=useState(''),[view,setView]=useState('map'),[selected,setSelected]=useState<string|null>(null);
 const [details,setDetails]=useState<{key:string;data:Details}|null>(null),[detailError,setDetailError]=useState('');
 const [registry,setRegistry]=useState<RegistryMachine[]|null>(null),[mapping,setMapping]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 const [preferences,setPreferences]=useState<Preferences>(defaults),[page,setPage]=useState(0);
 useEffect(()=>{const id=setTimeout(()=>{try{const saved=localStorage.getItem('relay:fleet-map:v3');const prefs=readPreferences(saved??localStorage.getItem('relay:fleet-map:v2')??localStorage.getItem('relay:fleet-map:v1'));setPreferences(window.location.hash==='#signwatch:sign-watch-test'?{...defaults}:saved?prefs:{...prefs,providers:[...new Set([...prefs.providers,'signwatch','roam'])]});}catch{}},0);return()=>clearTimeout(id);},[]);
 function updatePreferences(p:Preferences){setPreferences(p);setPage(0);try{localStorage.setItem('relay:fleet-map:v3',JSON.stringify(p));}catch{}}
 useEffect(()=>{if(!combined)return;const openAsset=()=>{if(window.location.hash==='#signwatch:sign-watch-test'){setSelected('signwatch:sign-watch-test');setPreferences({...defaults});setQuery('');setView('map');}};openAsset();window.addEventListener('hashchange',openAsset);return()=>window.removeEventListener('hashchange',openAsset);},[combined]);
 const panel=useRef<HTMLElement>(null),mapShell=useRef<HTMLDivElement>(null),fullScreenButton=useRef<HTMLButtonElement>(null);
 const [fullScreen,setFullScreen]=useState(false);
 useEffect(()=>{
  if(!fullScreen)return;
  const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';
  const shell=mapShell.current,trigger=fullScreenButton.current;shell?.focus();
  function keydown(e:KeyboardEvent){
   if(e.key==='Escape'){e.preventDefault();setFullScreen(false);}
   if(e.key==='Tab'&&shell){const nodes=Array.from(shell.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,textarea,[tabindex="0"]')).filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===shell)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===shell)){e.preventDefault();first?.focus();}}
  }
  document.addEventListener('keydown',keydown);
  return()=>{document.body.style.overflow=previousOverflow;document.removeEventListener('keydown',keydown);trigger?.focus();};
 },[fullScreen]);
 const statuses=useFleetStatuses(`${combined}:${provider}:${version}`,!!fleet&&(!combined||fleet.admin));
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');void request<Fleet>(combined?'combined':provider,'fleet',c.signal).then(d=>{if(!c.signal.aborted)setFleet(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[combined,provider,version,request]);
 const flagState=useAssetFlags(!!fleet?.admin);
 const signWatch=useSignWatch(combined&&!!fleet?.admin);
 const onHire=useOnHire(combined&&!!fleet?.admin,version);
 const allMachines=useMemo(()=>mergeRoamMap([...(fleet?.machines??[]),...(signWatch.machine?[signWatch.machine]:[])],combined&&fleet?.admin?onHire.hires:[]),[fleet,signWatch.machine,onHire.hires,combined]);
 const flaggedKeys=useMemo(()=>(fleet?.machines??[]).filter(m=>flagForMachine(flagState.flags,m)).map(machineKey),[fleet,flagState.flags]);

 const unmatchedHires=allMachines.filter(m=>m.source==='roam'&&!m.position).length;
 const machines=useMemo(()=>filterFleet(allMachines,combined?{...preferences,status:fleet?.admin?preferences.status:'all'}:{...preferences,status:preferences.status==='on_hire'?'all':preferences.status,providers:[provider],brand:'all',category:'all',group:'all'},query,statuses,Date.now(),onHire.ids),[fleet,allMachines,query,preferences,combined,provider,statuses,onHire.ids]);
 const shownPage=Math.min(page,Math.max(0,Math.ceil(machines.length/60)-1));
 const machine=allMachines.find(m=>machineKey(m)===selected);
 const choose=useCallback((key:string)=>{setSelected(key);setMapping('');setNotice('');},[]);
 useEffect(()=>{if(!fullScreen&&selected&&window.innerWidth<=1000)panel.current?.scrollIntoView({behavior:'smooth',block:'start'});},[selected,fullScreen]);
 useEffect(()=>{if(!machine||machine.source==='signwatch'||machine.source==='roam'||(combined&&!fleet?.admin))return;const c=new AbortController();setDetailError('');void request<Details>(machine.source??'jcb',`machine?${new URLSearchParams({pin:machine.pin})}`,c.signal).then(data=>{if(!c.signal.aborted)setDetails({key:machineKey(machine),data});}).catch(e=>{if(!c.signal.aborted)setDetailError(e.message);});return()=>c.abort();},[machine,version,request,combined,fleet?.admin]);
 const current=combined&&!fleet?.admin?null:details?.key===selected?details.data:null;
 const display=current?.machine??machine;
 const href=display?partsRequestUrl(display):null;
 async function openLinking(){try{const result=await request<{registry:RegistryMachine[]}>(machine?.source??provider,'manage');setRegistry(result.registry);}catch(e){setNotice(e instanceof Error?e.message:'Unable to load linking.');}}
 async function link(){if(!machine||!mapping)return;setSaving(true);try{await request(machine.source??provider,'manage',undefined,{action:'mapping',pin:machine.pin,machineId:mapping});setNotice('Machine link saved.');setRegistry(null);setVersion(v=>v+1);}catch(e){setNotice(e instanceof Error?e.message:'Unable to link machine.');}finally{setSaving(false);}}
 function exportCsv(){if(!fleet?.admin)return;const cell=(x:unknown)=>'"'+String(x??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const rows:unknown[][]=[['Provider','RELAY machine','Fleet number','Machine reference','Model','Latitude','Longitude','Position reported','Address / road','Operating hours','Battery voltage','Ignition','Odometer (km)','Speed (mph)','Heading','Make','Group','Asset type']];for(const m of machines)rows.push([machineProvider(m),m.relay?.machine_number,m.equipmentId,m.pin,m.model,m.position?.latitude,m.position?.longitude,m.position?.at,m.position?.address??m.travel?.road,m.hours?.value,m.batteryVoltage?.value,m.ignition?.value===true?'On':m.ignition?.value===false?'Off':'',m.odometer?.value,m.travel?.speedMph,m.travel?.heading,machineBrand(m),m.assetGroup,m.assetCategory]);const url=URL.createObjectURL(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='RELAY-fleet-positions.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="jcb-workspace"><header className="jcb-toolbar"><div><h1>{combined?'FLEET MAP':provider==='takeuchi'?'Takeuchi Track':'Manitou Track'}</h1><p>{combined?'Plant and vehicle tracking in one view.':'Machine positions, dated faults and RELAY parts requests.'}</p></div><div className="jcb-actions"><button disabled={loading} onClick={()=>setVersion(v=>v+1)}>{loading?'Loading…':'Refresh view'}</button>{fleet?.admin&&<><button onClick={exportCsv}>Export positions CSV</button><Link className="jcb-button" href="/fleet/hires">ROAM hires</Link><Link className="jcb-button" href="/fleet/scheduler">Fleet scheduler</Link><Link className="jcb-button" href="/reports?tab=fleet">Fleet Health</Link></>}{fleet&&<Link className="jcb-button" href="/fleet/register">Fleet register</Link>}</div></header>
 {error&&<p role="alert" className="jcb-warning">{error} {fleet?'Showing previously loaded data.':''}</p>}
 {fleet?.admin&&flagState.error&&<p role="alert" className="jcb-warning">{flagState.error} <button onClick={flagState.refresh}>Retry flags</button></p>}
 {notice&&<p role="status" className="jcb-notice">{notice}</p>}
 {fleet&&<><div className="tracking-sources">{(fleet.sources??[{provider,available:true,count:fleet.machines.length,checkedAt:fleet.checkedAt??null,stale:!!fleet.stale}]).map(s=><div className={!s.available||s.stale?'jcb-warning':'jcb-sync'} key={s.provider}><strong>{s.provider==='assetcare'?'Asset Care+':s.provider==='takeuchi'?'Takeuchi Track':s.provider==='jcb'?'JCB LiveLink':'Manitou Track'}</strong> · {s.available?`${s.count} machines · fetched ${date(s.checkedAt)}`:'Connection unavailable — this fleet is missing from the map'}{s.stale&&s.available?' · Cached data is out of date':''}</div>)}</div><p className="jcb-sync">Readings are cached for up to 15 minutes. Check the position timestamp before travelling. Map pins: teal JCB, red Manitou, purple Takeuchi, blue Asset Care+ and amber for a position not checked in. Card colours show the status below.</p>
 <div className="jcb-toolbar"><label className="jcb-search">Find a machine<input placeholder="Fleet number, model or PIN" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label><div className="jcb-actions"><button aria-pressed={view==='map'} onClick={()=>setView('map')}>Map view</button><button aria-pressed={view==='list'} onClick={()=>setView('list')}>List view</button>{fleet.admin&&<button aria-pressed={view==='flagged'} onClick={()=>{setView('flagged');setFullScreen(false);}}>⚑ Flagged ({flagState.ready?flagState.flags.length:'…'})</button>}</div></div>
 {fleet.groupError&&<p role="status" className="jcb-warning">Asset groups could not be loaded. Refresh to retry.</p>}
 {combined&&<MapPreferences showStatus={fleet.admin} value={preferences} onChange={updatePreferences} machines={allMachines}/>}
 {combined&&fleet.admin&&<p role={onHire.error?'alert':'status'} className={onHire.error?'jcb-warning':'jcb-sync'}>{onHire.error||(!onHire.checkedAt?'Loading ROAM on-hire machines…':`ROAM on hire: ${onHire.hires.length} hire records · checked ${date(onHire.checkedAt)} · updates every minute. ${unmatchedHires} ROAM assets have no usable site or delivery coordinates. ROAM pins are hire locations, not live GPS.`)} <Link href="/fleet/hires">View all ROAM hires</Link></p>}
 {fleet.assetcareStatus&&<p className={fleet.assetcareStatus.last_error?'jcb-warning':'jcb-sync'}>Asset Care+ collection: last attempted {date(fleet.assetcareStatus.last_attempt_at)} · last saved and acknowledged {date(fleet.assetcareStatus.last_ack_at)}. {fleet.assetcareStatus.last_error} {(!fleet.assetcareStatus.last_ack_at||Date.now()-Date.parse(fleet.assetcareStatus.last_ack_at)>86400000)&&'Check collection: the export can disable after seven days without use.'}</p>}
 {fleet.admin&&fleet.assetcareStatus&&<CollectionHealth state={fleet.assetcareStatus}/>}
 {(!combined||fleet.admin)&&<FleetStatusLegend/>}{view==='flagged'&&fleet.admin?<FlaggedList flags={flagState.flags} machines={allMachines} query={query} ready={flagState.ready} onRefresh={flagState.refresh} onSelect={key=>{setQuery('');setPreferences(p=>({...defaults,base:p.base,cluster:p.cluster,labels:p.labels,yard:p.yard}));choose(key);setView('map');}}/>:<div ref={mapShell} tabIndex={-1} role={fullScreen?'dialog':undefined} aria-modal={fullScreen||undefined} aria-label={fullScreen?'Full screen fleet map':undefined} className={`fleet-map-shell${fullScreen?' fleet-map-fullscreen':''}${selected?' fleet-map-has-selection':''}${combined&&view==='map'?' fleet-map-focused':''}`}>
 {view==='map'&&<div className="fleet-fullscreen-toolbar"><strong>{fullScreen?'Fleet map':''}</strong>{fullScreen&&<label>Find machine<input aria-label="Find machine in full screen" placeholder="Fleet number, model or PIN" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label>}<button ref={fullScreenButton} onClick={()=>setFullScreen(v=>!v)}>{fullScreen?'Exit full screen':'Full screen map'}</button></div>}
 <div className="jcb-grid"><section className="jcb-results" aria-label="Tracked machines">{view==='map'&&<FleetMap machines={machines} selectedPin={selected} onSelect={choose} showYard={preferences.yard} labels={preferences.labels} cluster={preferences.cluster} base={preferences.base} sidePanel={fullScreen||combined} flaggedKeys={flaggedKeys}/>}<p>{machines.length} shown · {machines.filter(m=>!m.position).length} without a map position</p>{view==='list'&&<><div className="jcb-machine-list">{machines.slice(shownPage*60,shownPage*60+60).map(m=><button className={`jcb-machine fleet-card-${statuses[machineKey(m)]?.tone??'unknown'} ${selected===machineKey(m)?'selected':''}`} key={machineKey(m)} aria-pressed={selected===machineKey(m)} onClick={()=>choose(machineKey(m))}><strong>{m.relay?.machine_number||m.equipmentId} · {machineBrand(m)} {m.model}</strong>{fleet.admin&&flagForMachine(flagState.flags,m)&&<span className="fleet-flag-badge">⚑ Flagged</span>}<span>{m.source==='roam'?'ROAM hire location · No live GPS':m.position?positionAge(m.position.at):'Position unavailable'}</span>{m.source==='roam'?<span>On hire · {m.roamHire?.site}</span>:m.source==='signwatch'?<span role="status">{signWatch.state.label}</span>:(!combined||fleet.admin)&&<FleetStatus status={statuses[machineKey(m)]}/>}<small>{m.assetGroup?`${m.assetGroup} · ${m.assetCategory} · `:''}{m.source==='assetcare'?'Asset Care+ · ':''}{m.source==='roam'?<span>On hire · {m.roamHire?.site}</span>:m.source==='signwatch'?'Test':m.relay?'Linked to RELAY':'Needs RELAY linking'}</small></button>)}{!machines.length&&<p>No machines match this filter.</p>}</div>{machines.length>60&&<nav className="jcb-actions" aria-label="Asset pages"><button disabled={shownPage===0} onClick={()=>setPage(shownPage-1)}>Previous</button><span>Page {shownPage+1} of {Math.ceil(machines.length/60)}</span><button disabled={(shownPage+1)*60>=machines.length} onClick={()=>setPage(shownPage+1)}>Next</button></nav>}</>}</section>
 <section ref={panel} className="jcb-detail" aria-label="Selected machine">{(fullScreen||combined)&&<button className="fleet-close-detail" onClick={()=>setSelected(null)}>Close machine details ×</button>}{!display?<><h2>Select a machine</h2><p>Choose a map pin or machine to see its position and faults, or raise a parts request.</p></>:display.source==='roam'?<RoamMapDetails machine={display}/>:display.source==='signwatch'?<SignWatchAssetDetails sensor={signWatch}/>:<><h2>{display.relay?.machine_number||display.equipmentId} · {machineBrand(display)}</h2><p>{display.model}</p>{display.relay&&(!combined||fleet.admin)&&<Link className="jcb-button" href={`/assets/${display.relay.id}`}>Machine record</Link>}{(!combined||fleet.admin)&&<FleetStatus status={statuses[machineKey(display)]}/>}{fleet.admin&&display.relay&&<AssetHireLink key={display.relay.id} machineId={display.relay.id}/>}<p className="jcb-sync">Machine reference: {display.pin}</p>{fleet.admin&&<FlagMachine key={`${machineKey(display)}:${flagForMachine(flagState.flags,display)?.id??'none'}`} machine={display} flag={flagForMachine(flagState.flags,display)} ready={flagState.ready} onSaved={flagState.refresh}/>}{fleet.admin&&<AssetTravel key={machineKey(display)} machine={display}/>}<h3>Last-known position</h3>{display.position?<><p>{date(display.position.at)} · {positionAge(display.position.at)}</p><a className="jcb-button" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${display.position.latitude},${display.position.longitude}`}>Directions to this position</a><LocationViews position={display.position}/>{fleet.admin&&<ShareAssetLocation key={`${display.source}:${display.pin}`} machine={display}/>}</>:<p>No valid position supplied.</p>}
 {href?<Link className="jcb-button jcb-primary" href={href}>Raise RELAY parts request</Link>:<p className="jcb-warning">An admin must confirm the RELAY machine link before a request can be prefilled.</p>}
 {fleet.admin&&(display.source==='trackunit'||display.source==='takeuchi')&&<button className="jcb-button" onClick={()=>void openLinking()}>Confirm / change RELAY link</button>}
 {registry&&(display.source==='trackunit'||display.source==='takeuchi')&&<div className="tracking-link"><p>Verify the full machine reference against the RELAY record before saving.</p><label>RELAY machine<select value={mapping} onChange={e=>setMapping(e.target.value)}><option value="">Select verified machine</option>{registry.filter(r=>(r.make??'').toUpperCase().startsWith(machine?.source==='takeuchi'?'TAKEUCHI':'MANITOU')).map(r=><option key={r.id} value={r.id}>{r.machine_number} · {r.model} · {r.serial_number||'No serial'}</option>)}</select></label><button disabled={!mapping||saving} onClick={()=>void link()}>Save verified link</button><button onClick={()=>setRegistry(null)}>Cancel</button></div>}
 {combined&&!fleet.admin?<p className="jcb-sync">Directions use the last-known position shown above. Check its reported time before travelling.</p>:detailError?<p role="alert" className="jcb-warning">{detailError}</p>:!current?<p>Loading machine readings…</p>:<>{fleet.admin&&<><h3>Reported condition</h3><dl className="jcb-metrics">{(['hours','fuel','adblue'] as const).map(key=><div key={key}><dt>{key==='hours'?'Operating hours':key==='fuel'?'Fuel':'AdBlue'}</dt><dd>{display[key]?`${display[key]!.value}${key==='hours'?' h':'%'}`:'Not supplied'}</dd><small>{display[key]?date(display[key]!.at):''}</small></div>)}</dl>{current.telemetryError&&<p className="jcb-warning">Telemetry unavailable. These readings have not been assessed.</p>}{current.telemetry&&<details className="tracking-readings" open={display.source==='assetcare'?true:undefined}><summary>All reported readings ({current.telemetry.length})</summary><p>Provider readings with their original units and times. Older readings are last known values. Raw codes and counters are not converted when their units or meaning are unconfirmed. Confirm warning states on the machine.</p>{current.telemetry.map((t,i)=><div key={`${t.name}-${i}`}><strong>{t.name}</strong><span>{String(t.value??'Not supplied')} {t.uoM}</span><small>{date(t.time)}</small></div>)}</details>}</>}{current.faultError?<p className="jcb-warning">{display.source==='assetcare'?'Asset Care+ fault-code coverage is not confirmed. Do not treat this as an all-clear.':'Fault records unavailable. Retry before assessing this machine.'}</p>:<FaultCards machine={display} faults={current.faults} checkedAt={current.checkedAt}/>}</>}
 </>}</section></div></div>}</>}
 </div>;
}
