'use client';
import {useEffect,useState} from 'react';
import {getSupabaseAccessToken} from '@/lib/supabase';
import {signWatchState,type SignWatchFeed} from '@/lib/sign-watch/model';
import './style.css';
export function SignWatchFleetCard(){
 const [feed,setFeed]=useState<SignWatchFeed|null>(null),[error,setError]=useState(''),[now,setNow]=useState(()=>Date.now()),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;const controller=new AbortController();
  async function load(){try{const token=await getSupabaseAccessToken();if(!token)throw Error('Sign in to view Sign Watch.');const response=await fetch('/api/sign-watch',{headers:{Authorization:`Bearer ${token}`},cache:'no-store',signal:controller.signal});const data=await response.json();if(!response.ok)throw Error(data.error||'Unable to load Sign Watch.');if(active){setFeed(data);setError('');}}catch(e){if(active)setError(e instanceof Error?e.message:'Unable to load Sign Watch.');}finally{if(active){setLoading(false);setNow(Date.now());timer=setTimeout(load,5000);}}}
  void load();const clock=setInterval(()=>setNow(Date.now()),1000);return()=>{active=false;clearTimeout(timer);clearInterval(clock);controller.abort();};
 },[]);
 const s=signWatchState(feed,now,!!error),angle=(v:number|null)=>v===null?'—':`${v.toFixed(1)}°`;
 const badge=loading?'Connecting…':s.label;
 return <section className="sign-watch-card" aria-label="Sign Watch Test" id="sign-watch-test">
  <div className="sign-watch-heading"><div><span className="sign-watch-kicker">LIVE PROTOTYPE · CONE TILT TEST</span><h2>Sign Watch Test</h2></div><span className={`sign-watch-badge ${s.live&&s.reading?.status==='level'?'is-level':s.reading?.status==='fallen'&&s.live?'is-fallen':''}`} role="status">{badge}</span></div>
  <div className="sign-watch-content"><div className="sign-watch-cone"><svg viewBox="0 0 180 170" role="img" aria-label={s.tilt===null?'Cone illustration; current tilt unavailable':`Cone tilt ${angle(s.tilt)}`}><defs><linearGradient id="sw-orange"><stop stopColor="#fa7427"/><stop offset=".55" stopColor="#ffab59"/><stop offset="1" stopColor="#d65c19"/></linearGradient></defs><path d="M15 147H165M90 12V147" stroke="#8495aa" strokeDasharray="4 5" opacity=".4"/><g transform={`rotate(${s.tilt===null?0:Math.min(120,s.tilt)*(s.roll!==null&&s.roll<0?-1:1)},90,139)`}><path d="M47 135L88 123L137 136L96 153Z" fill="#273341"/><path d="M81 28Q89 24 97 28L121 133Q91 146 62 132Z" fill="url(#sw-orange)"/><path d="M77 48Q90 52 102 48L107 71Q91 77 72 71Z" fill="#f0f3ef"/><path d="M68 89Q90 97 111 89L116 111Q91 122 64 110Z" fill="#f0f3ef"/></g></svg><small>{s.calibrated?'Tilt illustration':'Awaiting live calibration'}</small></div>
  <div className="sign-watch-data"><dl><div><dt>Tilt from upright</dt><dd>{angle(s.tilt)}</dd></div><div><dt>Forward / back</dt><dd>{angle(s.pitch)}</dd></div><div><dt>Left / right</dt><dd>{angle(s.roll)}</dd></div></dl><p><strong>Calibration:</strong> {s.reading?.calibrated?'Upright reference saved':'Not calibrated'}{s.reading?.calibrated_at&&` · ${new Date(s.reading.calibrated_at).toLocaleString('en-GB')}`}</p><p><strong>GPS:</strong> {s.location?<a href={`https://www.google.com/maps/search/?api=1&query=${s.location.latitude},${s.location.longitude}`} target="_blank" rel="noreferrer">{s.location.latitude.toFixed(6)}, {s.location.longitude.toFixed(6)} ↗</a>:s.live?'No fresh GPS fix':'Location unavailable while offline'}{s.location&&` · ${s.reading?.gps.satellites} satellites`}</p><p><strong>Last received:</strong> {feed?.latest?new Date(feed.latest.received_at).toLocaleString('en-GB'):'Waiting for sensor data'}</p></div></div>
  {error&&<p role="alert" className="sign-watch-error">{error}</p>}
  <details><summary>Test thresholds and calibration</summary><p>Level: below 15°. Fallen: at least 60° held still for 2 seconds. Recovery: below 45° for 2 seconds. Rapid movement is shown separately. Set the upright reference using the calibration page on the Mac connected to the prototype. This Fleet card is read-only.</p><p>Updates every 5 seconds. The USB bridge and connected Mac must remain running. Stale readings are marked offline.</p></details>
 </section>;
}
