'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {date} from './workspace';
import {assetRequest} from './request';
import './workspace.css';
type Item={id:string;machine_id:string;kind:string;title:string;detail:string;occurred_at:string;read_at:string|null;acknowledged_at:string|null;machine?:{machine_number:string;make:string;model:string}};
export function AssetInbox(){const [kind,setKind]=useState(''),[unread,setUnread]=useState(true),[rows,setRows]=useState<Item[]>([]),[next,setNext]=useState<number|null>(null),[before,setBefore]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[version,setVersion]=useState(0),[enabled,setEnabled]=useState(true),[offset,setOffset]=useState(0),[saving,setSaving]=useState<string|null>(null);
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');if(offset===0)setRows([]);const params=new URLSearchParams({unread:String(unread),offset:String(offset)});if(kind)params.set('kind',kind);if(offset&&before)params.set('before',before);void assetRequest<{rows:Item[];next:number|null;before:string;enabled:boolean}>(`/api/assets/inbox?${params}`,c.signal).then(d=>{if(c.signal.aborted)return;setRows(old=>offset?[...old,...d.rows]:d.rows);setNext(d.next);if(offset===0)setBefore(d.before);setEnabled(d.enabled);}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();
 // The first page freezes the time boundary; subsequent pages retain it.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[kind,unread,version,offset]);
 async function act(id:string,action:string){setSaving(id);setError('');try{await assetRequest('/api/assets/inbox',undefined,{id,action});window.dispatchEvent(new Event('asset-inbox-changed'));setRows(old=>unread?old.filter(r=>r.id!==id):old.map(r=>r.id===id?{...r,read_at:new Date().toISOString(),acknowledged_at:action==='acknowledge'?new Date().toISOString():r.acknowledged_at}:r));if(unread){setOffset(0);setVersion(v=>v+1);}}catch(e){setError(e instanceof Error?e.message:'Unable to update item');}finally{setSaving(null);}}
 return <section className="asset-workspace"><div className="asset-heading"><div><p className="asset-eyebrow">Fleet updates</p><h1>Asset Inbox</h1><p>Movements, reported faults and tracking issues. No pop-ups or sounds.</p></div><Link className="asset-button" href="/assets">Asset Search</Link></div><div className="asset-filters"><label>Show <select value={kind} onChange={e=>{setKind(e.target.value);setOffset(0);}}><option value="">All updates</option><option value="movement">Movements</option><option value="yard_arrival">Returned to Yard</option><option value="yard_departure">Yard departures</option><option value="fault">Fault codes</option><option value="not_checked_in">Not checked in</option><option value="data_unavailable">Data unavailable</option></select></label><label><input type="checkbox" checked={unread} onChange={e=>{setUnread(e.target.checked);setOffset(0);}}/> Unread only</label><button disabled={busy} onClick={()=>{setOffset(0);setVersion(v=>v+1);}}>Refresh</button></div>{!enabled&&<p role="status">Automatic inbox collection is awaiting activation.</p>}{error&&<p role="alert">{error}</p>}<p>Fault entries show the latest report for each machine and code. Read and acknowledged states are personal to each administrator. Acknowledging a fault does not mark it repaired.</p><p role="status">{busy?'Loading asset updates…':`${rows.length} items shown`}</p>{!busy&&!error&&!rows.length&&<article className="asset-card"><h2>No {unread?'unread ':''}updates</h2><p>New events appear after scheduled fleet collection. This does not confirm that every machine is healthy.</p></article>}{rows.map(r=><article className={`asset-inbox-item ${r.read_at?'':'asset-unread'}`} key={r.id}><div><strong>{r.machine?.machine_number||'Machine'} · {r.kind==='yard_arrival'?'Returned to Yard':r.title}</strong><p>{r.detail}</p><small>{r.machine?.make} {r.machine?.model} · Reported {date(r.occurred_at)}</small>{r.acknowledged_at&&<p>Acknowledged {date(r.acknowledged_at)}</p>}</div><div className="asset-actions"><Link href={`/assets/${r.machine_id}`}>View machine</Link><Link href={`/submit?machineReference=${encodeURIComponent(r.machine?.machine_number??'')}&asset=${encodeURIComponent(r.machine_id)}`}>Raise parts request</Link>{!r.read_at&&<button disabled={saving===r.id} onClick={()=>void act(r.id,'read')}>Mark read</button>}{!r.acknowledged_at&&<button disabled={saving===r.id} onClick={()=>void act(r.id,'acknowledge')}>Acknowledge</button>}</div></article>)}{next!==null&&<button disabled={busy} onClick={()=>setOffset(next)}>Load more</button>}</section>;
}
