'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {buildFleetOverview} from '@/lib/assets/overview';
import type {LinkedJcbMachine} from '@/lib/integrations/jcb/types';
import {assetRequest} from './request';
import './workspace.css';

type FleetResponse={machines:LinkedJcbMachine[];checkedAt?:string;stale?:boolean;sources?:Array<{provider:string;available:boolean;count:number;checkedAt:string|null;stale:boolean}>};
type YardItem={id:string;machineId:string;label:string;model:string;kind:'yard_arrival'|'yard_departure';at:string;provider:string};
type OperationsResponse={yard:{returnedToday:YardItem[];leftToday:YardItem[];recent:YardItem[];longest:YardItem[]};attention:{flags:Array<{id:string;label:string;reason:string;created_at:string;machine_id:string|null}>;openPartsRequests:number|null;assetsWithOpenPartsRequests:number|null}};
const date=(value?:string)=>value?new Date(value).toLocaleString('en-GB',{timeZone:'Europe/London'}):'Time unavailable';

export function AssetOverviewDashboard(){
 const [data,setData]=useState<FleetResponse|null>(null),[operations,setOperations]=useState<OperationsResponse|null>(null),[error,setError]=useState('');
 const [coverageView,setCoverageView]=useState<'recent'|'stale'|'missing'|null>(null);
 useEffect(()=>{const controller=new AbortController();assetRequest<FleetResponse>('/api/integrations/combined/fleet',controller.signal).then(result=>{if(!controller.signal.aborted)setData(result);}).catch(reason=>{if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:'Fleet overview unavailable.');});assetRequest<OperationsResponse>('/api/assets/overview',controller.signal).then(result=>{if(!controller.signal.aborted)setOperations(result);}).catch(()=>{});return()=>controller.abort();},[]);
 const overview=useMemo(()=>data?buildFleetOverview(data.machines):null,[data]);
 return <section className="asset-overview-dashboard" aria-labelledby="fleet-overview-title">
  <header className="asset-overview-heading"><div><p className="asset-eyebrow">Fleet &amp; Assets</p><h1 id="fleet-overview-title">Overview</h1><p>Latest known fleet position and tracker coverage.</p></div><div className="asset-overview-actions"><Link href="/fleet/map">Open Fleet Map</Link><Link href="/assets/inbox">View Alerts</Link></div></header>
  {error&&<p className="asset-overview-warning" role="alert">{error}</p>}
  {!overview?<p className="asset-overview-loading" role="status">Loading fleet overview…</p>:<>
   <div className="asset-overview-metrics" aria-label="Fleet location summary">
    <article className="is-total"><span>Tracked Assets</span><strong>{overview.total}</strong><small>Across all connected providers</small></article>
    <article className="is-yard"><span>Inside MLP Yard</span><strong>{overview.inside}</strong><small>Latest valid position is inside the geofence</small></article>
    <article className="is-away"><span>Outside MLP Yard</span><strong>{overview.outside}</strong><small>Latest valid position is outside the geofence</small></article>
   </div>
   <div className="asset-overview-panels">
    <article><header><div><p className="asset-eyebrow">Tracker Coverage</p><h2>Latest Check-In</h2></div><span>{data?.stale?'Cached data':'Live snapshot'}</span></header><div className="asset-checkin-bars"><button type="button" aria-pressed={coverageView==='recent'} onClick={()=>setCoverageView(coverageView==='recent'?null:'recent')}><span>Within 24 hours</span><strong>{overview.checkedIn24h}</strong><i style={{width:`${overview.total?overview.checkedIn24h/overview.total*100:0}%`}}/></button><button type="button" aria-pressed={coverageView==='stale'} onClick={()=>setCoverageView(coverageView==='stale'?null:'stale')}><span>Over 24 hours</span><strong>{overview.over24h}</strong><i style={{width:`${overview.total?overview.over24h/overview.total*100:0}%`}}/></button><button type="button" aria-pressed={coverageView==='missing'} onClick={()=>setCoverageView(coverageView==='missing'?null:'missing')}><span>No check-in time</span><strong>{overview.neverCheckedIn}</strong><i style={{width:`${overview.total?overview.neverCheckedIn/overview.total*100:0}%`}}/></button></div><small>Click a row to inspect the affected assets · Snapshot updated {date(data?.checkedAt)}</small></article>
    <article><header><div><p className="asset-eyebrow">Cost Centres</p><h2>Location Breakdown</h2></div><Link href="/fleet/map">View on Map</Link></header><div className="asset-overview-table"><table><thead><tr><th>Group</th><th>Total</th><th>Yard</th><th>Outside</th></tr></thead><tbody>{overview.groups.map(group=><tr key={group.name}><td>{group.name}</td><td>{group.total}</td><td>{group.inside}</td><td>{group.outside}</td></tr>)}</tbody></table></div></article>
   </div>
   {coverageView&&<section className="asset-coverage-detail" aria-live="polite"><header><div><p className="asset-eyebrow">Tracker Detail</p><h2>{coverageView==='recent'?'Checked In Within 24 Hours':coverageView==='stale'?'Needs Attention · Over 24 Hours':'Needs Attention · No Check-In Time'}</h2></div><button type="button" onClick={()=>setCoverageView(null)}>Close</button></header><div>{overview.coverage[coverageView].map(asset=><article key={asset.key}><div><strong>{asset.label}</strong><span>{asset.model||'Model not supplied'} · {asset.group}</span></div><time>{asset.reportedAt?date(asset.reportedAt):'No check-in time supplied'}</time>{asset.id?<Link href={`/assets/${asset.id}`}>Open Record</Link>:<Link href="/fleet/map">Find on Map</Link>}</article>)}{!overview.coverage[coverageView].length&&<p>No assets in this group.</p>}</div></section>}
   <div className="asset-ops-grid">
    <article><header><p className="asset-eyebrow">Yard Movements Today</p><h2>MLP Yard Activity</h2></header>{operations?<div className="asset-ops-counts"><details><summary><strong>{operations.yard.returnedToday.length}</strong><span>Returned to Yard</span></summary><YardRows rows={operations.yard.returnedToday}/></details><details><summary><strong>{operations.yard.leftToday.length}</strong><span>Left MLP Yard</span></summary><YardRows rows={operations.yard.leftToday}/></details></div>:<p>Movement history unavailable for this account.</p>}</article>
    <article><header><p className="asset-eyebrow">Assets Moving Now</p><h2>Current Evidence</h2></header><div className="asset-ops-counts"><AssetDisclosure label="In Transit" rows={overview.movement.transit}/><AssetDisclosure label="Stationary" rows={overview.movement.stationary}/><AssetDisclosure label="Ignition On" rows={overview.movement.ignitionOn}/></div><small>Only recent provider evidence is counted; missing telemetry is not treated as stationary.</small></article>
    <article><header><p className="asset-eyebrow">Longest in Yard</p><h2>Recorded Yard Dwell</h2></header>{operations?<YardRows rows={operations.yard.longest} dwell/>:<p>Yard history unavailable.</p>}<small>Measured from the latest recorded return with no later departure.</small></article>
    <article><header><p className="asset-eyebrow">Recent Activity</p><h2>Arrivals &amp; Departures</h2></header>{operations?<YardRows rows={operations.yard.recent}/>:<p>Activity unavailable.</p>}</article>
    <article><header><p className="asset-eyebrow">Provider Health</p><h2>Connected Feeds</h2></header><div className="asset-provider-list">{(data?.sources??overview.distribution.providers.map(row=>({provider:row.name,available:true,count:row.count,checkedAt:data?.checkedAt??null,stale:false}))).map(source=><div key={source.provider}><span>{providerName(source.provider)}</span><strong>{source.count}</strong><small className={!source.available||source.stale?'needs-attention':''}>{!source.available?'Unavailable':source.stale?'Stale':`Checked ${date(source.checkedAt??undefined)}`}</small></div>)}</div></article>
    <article><header><p className="asset-eyebrow">Fleet Distribution</p><h2>What We Track</h2></header><div className="asset-distribution"><Breakdown title="Cost Centre" rows={overview.groups.map(row=>({name:row.name,count:row.total}))}/><Breakdown title="Manufacturer" rows={overview.distribution.manufacturers}/><Breakdown title="Category" rows={overview.distribution.categories}/></div></article>
    <article><header><p className="asset-eyebrow">Battery Attention</p><h2>Latest Voltage</h2></header><div className="asset-attention-stats"><span><strong>{overview.battery.attention.length}</strong> below 11.8 V</span><span><strong>{overview.battery.reported}</strong> reporting voltage</span><span><strong>{overview.battery.missing}</strong> without a reading</span></div>{overview.battery.attention.length?<AssetRows rows={overview.battery.attention}/>:<p>No reported readings below the review threshold.</p>}<small>Voltage alone is not a diagnosis; confirm the machine’s electrical system and reading time.</small></article>
    <article><header><p className="asset-eyebrow">Open Attention Items</p><h2>Needs Review</h2></header><div className="asset-attention-stats"><Link href="/assets/inbox"><strong>{operations?.attention.flags.length??'—'}</strong> flagged assets</Link><Link href="/requests"><strong>{operations?.attention.openPartsRequests??'—'}</strong> open parts requests</Link><Link href="/fleet/map"><strong>{overview.attention.unmatched}</strong> unmatched cost centres</Link><Link href="/fleet/map"><strong>{overview.attention.unlinked}</strong> assets needing fleet linking</Link></div>{operations?.attention.flags.slice(0,5).map(flag=><p className="asset-flag-summary" key={flag.id}><strong>{flag.label}</strong><span>{flag.reason}</span></p>)}</article>
   </div>
   <p className="asset-overview-note">Inside and outside figures use each asset’s latest valid saved GPS position against the MLP Yard geofence. They show last-known location, not contractual hire status or current movement.</p>
  </>}
 </section>;
}

function providerName(value:string){return value==='assetcare'?'Asset Care+':value==='jcb'?'JCB LiveLink':value==='trackunit'?'Manitou':value==='takeuchi'?'Takeuchi':value;}
function AssetRows({rows}:{rows:ReturnType<typeof buildFleetOverview>['coverage']['recent']}){return <div className="asset-mini-list">{rows.slice(0,12).map(row=><div key={row.key}><span><strong>{row.label}</strong><small>{row.model} · {row.group}</small></span>{row.id?<Link href={`/assets/${row.id}`}>Open</Link>:<Link href="/fleet/map">Map</Link>}</div>)}{!rows.length&&<p>No assets in this group.</p>}{rows.length>12&&<small>Showing 12 of {rows.length}</small>}</div>;}
function AssetDisclosure({label,rows}:{label:string;rows:ReturnType<typeof buildFleetOverview>['coverage']['recent']}){return <details><summary><strong>{rows.length}</strong><span>{label}</span></summary><AssetRows rows={rows}/></details>;}
function YardRows({rows,dwell=false}:{rows:YardItem[];dwell?:boolean}){const now=Date.now();return <div className="asset-mini-list">{rows.slice(0,12).map(row=><div key={row.id}><span><strong>{row.label}</strong><small>{row.model} · {dwell?duration(now-Date.parse(row.at)):row.kind==='yard_arrival'?'Returned':'Departed'} · {date(row.at)}</small></span><Link href={`/assets/${row.machineId}`}>Open</Link></div>)}{!rows.length&&<p>No recorded assets.</p>}</div>;}
function Breakdown({title,rows}:{title:string;rows:Array<{name:string;count:number}>}){return <section><h3>{title}</h3>{rows.slice(0,6).map(row=><div key={row.name}><span>{row.name}</span><strong>{row.count}</strong></div>)}</section>;}
function duration(ms:number){if(!Number.isFinite(ms)||ms<0)return 'Unknown duration';const days=Math.floor(ms/86400000),hours=Math.floor(ms%86400000/3600000);return days?`${days}d ${hours}h in yard`:`${hours}h in yard`;}
