'use client';
import './share-location.css';
import {useState} from 'react';
import type {LinkedJcbMachine} from '@/lib/integrations/jcb/types';
import {assetJobSchema,locationShare} from '@/lib/assets/share';
import {assetRequest} from './request';
export function ShareAssetLocation({machine}:{machine:LinkedJcbMachine}){
 const [open,setOpen]=useState(false),[fitters,setFitters]=useState<{id:string;name:string}[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[requestId,setRequestId]=useState('');
 const share=locationShare(machine);if(!share)return null;
 async function openJob(){setOpen(true);setMessage('');setError('');setRequestId(crypto.randomUUID());setBusy(true);try{setFitters((await assetRequest<{fitters:{id:string;name:string}[]}>('/api/assets/assign')).fitters);}catch(e){setError(e instanceof Error?e.message:'Unable to load fitters.');}finally{setBusy(false);}}
 return <section className="asset-share" aria-label="Share asset location"><h3>Share asset location</h3><div className="jcb-actions"><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(share.text);setMessage('Location copied to clipboard.');setError('');}catch{setError('Clipboard unavailable. Select and copy the location below.');}}}>Copy location</button><a className="jcb-button" href={`https://wa.me/?text=${encodeURIComponent(share.text)}`} target="_blank" rel="noopener noreferrer">WhatsApp ↗</a><button type="button" disabled={busy} onClick={()=>void openJob()}>Assign RELAY job</button></div><p className="jcb-sync">Shares the last reported position and its age. WhatsApp lets you choose who receives it.</p>{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}{error.startsWith('Clipboard')&&<textarea readOnly aria-label="Location to copy" value={share.text}/>}
 {open&&<form className="asset-job-form" onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget),payload={requestId,provider:machine.source??'jcb',pin:machine.pin,fitterId:data.get('fitterId'),jobNumber:data.get('jobNumber'),breakdown:data.get('breakdown'),contact:data.get('contact'),phone:data.get('phone')};const parsed=assetJobSchema.safeParse(payload);if(!parsed.success){setError('Complete all fields and enter a valid phone number.');return;}setBusy(true);setError('');try{await assetRequest('/api/assets/assign',undefined,parsed.data);setMessage('Job assigned. The fitter can find the details and location in Tasks.');setOpen(false);}catch(err){setError(err instanceof Error?err.message:'Unable to assign job.');}finally{setBusy(false);}}}>
 <h4>Assign job to a fitter</h4><label>Fitter<select name="fitterId" required disabled={busy}><option value="">Choose fitter</option>{fitters.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>{!busy&&!fitters.length&&<p>No enabled internal fitters are available.</p>}
 <label>Job number<input name="jobNumber" required maxLength={80} disabled={busy}/></label><label>Breakdown description<textarea name="breakdown" required maxLength={3000} disabled={busy}/></label><label>Site contact<input name="contact" required maxLength={150} disabled={busy}/></label><label>Phone number<input name="phone" type="tel" required maxLength={40} disabled={busy}/></label><p>The selected fitter receives these details and the asset’s dated location in RELAY Tasks.</p><div className="jcb-actions"><button type="submit" disabled={busy||!fitters.length}>{busy?'Please wait…':'Assign job'}</button><button type="button" disabled={busy} onClick={()=>setOpen(false)}>Cancel</button></div></form>}
 </section>;
}
