'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {assetRequest} from './request';
import type {RegistryMachine,LinkedJcbMachine,JcbFault} from '@/lib/integrations/jcb/types';
import {partsRequestUrl,positionAge} from '@/lib/integrations/jcb/types';
import {FaultCards} from '@/components/jcb/fault-cards';
import type {SmartSearchResponse} from '@/lib/admin-smart-search';
import type {movementHistory} from '@/lib/assets/events';
import './workspace.css';
import '@/components/jcb/health.css';
const AssetMap=dynamic(()=>import('@/components/jcb/livelink-map'),{ssr:false,loading:()=> <p>Loading map…</p>});
const HistoryMap=dynamic(()=>import('./movement-map'),{ssr:false,loading:()=> <p>Loading recorded positions…</p>});
export const date=(at:string|null|undefined)=>at?new Date(at).toLocaleString('en-GB',{timeZone:'Europe/London'}):'Not reported';

type SearchMachine=RegistryMachine&{position:LinkedJcbMachine['position'];provider:string|null};
export function AssetSearch(){
 const [q,setQ]=useState(''),[query,setQuery]=useState(''),[version,setVersion]=useState(0),[rows,setRows]=useState<SearchMachine[]>([]),[jobs,setJobs]=useState<SmartSearchResponse['results']>([]),[admin,setAdmin]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[total,setTotal]=useState(0);
 useEffect(()=>{if(query.length<2)return;const c=new AbortController();void assetRequest<{machines:SearchMachine[];admin:boolean;total:number;locationUnavailable:boolean}>(`/api/assets?q=${encodeURIComponent(query)}`,c.signal).then(async d=>{if(c.signal.aborted)return;setRows(d.machines);setAdmin(d.admin);setTotal(d.total);if(d.locationUnavailable)setError('Locations are temporarily unavailable; machine results are shown.');if(d.admin){try{const results=await Promise.all(['live','completed'].map(scope=>assetRequest<SmartSearchResponse>('/api/admin/search',c.signal,{query,scope})));if(!c.signal.aborted)setJobs([...new Map(results.flatMap(r=>r.results).filter(r=>r.entity!=='machine').map(r=>[r.href,r])).values()]);}catch{if(!c.signal.aborted)setError('Machine results loaded; related job search is unavailable.');}}}).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[query,version]);
 return <section className="asset-workspace"><div className="asset-heading"><div><p className="asset-eyebrow">MLP assets</p><h1>Asset Search</h1><p>Find a machine, its location, history and open work.</p></div>{admin&&<Link className="asset-button" href="/assets/inbox">Asset Inbox</Link>}</div><form className="asset-search" onSubmit={e=>{e.preventDefault();setBusy(true);setError('');setRows([]);setJobs([]);setQuery(q.trim());setVersion(v=>v+1);}}><label htmlFor="asset-query">Fleet number, serial, make, model or job reference</label><div><input id="asset-query" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="For example, 24001 or Takeuchi" maxLength={100}/><button disabled={busy||q.trim().length<2}>{busy?'Searching…':'Search'}</button></div></form>{error&&<p role="alert">{error}</p>}<p role="status">{busy?'Searching saved RELAY records…':query?`${total} matching machines${total>50?' · showing the first 50; refine your search':''}`:'Search to open a machine record. Provider APIs are checked only when needed.'}</p><div className="asset-grid">{rows.map(m=><Link className="asset-card" href={`/assets/${m.id}`} key={m.id}><strong>{m.machine_number}</strong><span>{m.make} {m.model}</span><small>Serial {m.serial_number||'not recorded'}</small><span>{m.position?`${positionAge(m.position.at)} · ${date(m.position.at)}`:'Location unavailable / not tracked'}</span><span className="asset-link">View location, work and history →</span></Link>)}</div>{jobs.length>0&&<section><h2>Related jobs and records</h2>{jobs.map(r=><Link className="asset-record" key={`${r.entity}:${r.id}`} href={r.href}><strong>{r.title}</strong><span>{r.subtitle}</span><small>{r.snippet} · {r.meta}</small></Link>)}</section>}</section>;
}
type Job={id:string;job_number:string|null;status:string;created_at:string;request_summary?:string;description?:string};
type Detail={machine:RegistryMachine;tracking:LinkedJcbMachine|null;checkedAt:string|null;admin:boolean;hire:{reason:string}|null;tickets:Job[];incidents:Job[];historyUnavailable:boolean;historyLimited:boolean};
export function AssetDetail({id}:{id:string}){
 const [data,setData]=useState<Detail|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('overview'),[days,setDays]=useState('7'),[points,setPoints]=useState<ReturnType<typeof movementHistory>|null>(null),[moveError,setMoveError]=useState(''),[truncated,setTruncated]=useState(false),[faults,setFaults]=useState<{faults:JcbFault[];faultError?:boolean;checkedAt:string}|null>(null),[faultError,setFaultError]=useState('');
 useEffect(()=>{const c=new AbortController();void assetRequest<Detail>(`/api/assets/${encodeURIComponent(id)}`,c.signal).then(d=>{if(!c.signal.aborted)setData(d);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[id]);
 useEffect(()=>{if(tab!=='movements')return;const c=new AbortController();void assetRequest<{points:ReturnType<typeof movementHistory>;truncated:boolean}>(`/api/assets/${encodeURIComponent(id)}?view=movements&days=${days}`,c.signal).then(d=>{if(!c.signal.aborted){setPoints(d.points);setTruncated(d.truncated);}}).catch(e=>{if(!c.signal.aborted)setMoveError(e.message);});return()=>c.abort();},[tab,days,id]);
 useEffect(()=>{if(tab!=='faults'||!data?.tracking)return;const c=new AbortController();void assetRequest<{faults:JcbFault[];faultError?:boolean;checkedAt:string}>(`/api/integrations/${data.tracking.source??'jcb'}/machine?pin=${encodeURIComponent(data.tracking.pin)}`,c.signal).then(d=>{if(!c.signal.aborted)setFaults(d);}).catch(e=>{if(!c.signal.aborted)setFaultError(e.message);});return()=>c.abort();},[tab,data]);
 if(error)return <p role="alert">{error}</p>;if(!data)return <p role="status">Loading asset…</p>;
 const m=data.tracking,request=m?partsRequestUrl(m):`/submit?machineReference=${encodeURIComponent(data.machine.machine_number)}`;
 return <section className="asset-workspace"><Link href="/assets">← Asset Search</Link><div className="asset-heading"><div><p className="asset-eyebrow">Machine record</p><h1>{data.machine.machine_number}</h1><p>{data.machine.make} {data.machine.model} · Serial {data.machine.serial_number||'not recorded'}</p></div><Link className="asset-button" href={request!}>Raise parts request</Link></div><nav className="asset-tabs" aria-label="Machine views">{[['overview','Overview'],['history','Work history'],['faults','Fault codes'],['movements','Movement history']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>{if(key===tab)return;setTab(key);setPoints(null);setMoveError('');setFaults(null);setFaultError('');}}>{label}</button>)}</nav>
 {tab==='overview'&&<><div className="asset-grid"><article className="asset-card"><h2>Last known location</h2><p>{m?.position?`${m.position.latitude.toFixed(5)}, ${m.position.longitude.toFixed(5)}`:'Location unavailable'}</p><p>{positionAge(m?.position?.at)} · {date(m?.position?.at)}</p><small>{data.hire?.reason}</small></article><article className="asset-card"><h2>Open parts requests</h2><strong>{data.historyUnavailable?'Unavailable':data.tickets.filter(t=>!['COMPLETED','CANCELLED'].includes(t.status)).length}{data.historyLimited?'+':''}</strong><button onClick={()=>setTab('history')}>View jobs</button></article>{data.admin&&m&&<article className="asset-card"><h2>Latest readings</h2><p>Engine: {m.hours?`${m.hours.value.toFixed(1)} h`:'Not supplied'}</p><small>{date(m.hours?.at)}</small><p>Idle: {m.idleHours?`${m.idleHours.value.toFixed(1)} h lifetime`:'Not supplied by provider'}</p><small>{date(m.idleHours?.at)}</small><p>Fuel: {m.fuel?`${m.fuel.value}%`:'Not supplied'}</p><small>{date(m.fuel?.at)} · Latest readings, not daily totals.</small></article>}</div>{m?.position&&<div className="asset-map"><AssetMap machines={[m]} selectedPin={null} onSelect={()=>{}} showYard/></div>}</>}
 {tab==='history'&&<><h2>Parts and workshop history</h2><p>Records available under your existing job permissions. {data.historyLimited?'Showing the latest 100 of each type; older records remain in the main registers.':''}</p>{data.historyUnavailable&&<p role="alert">Some job history is unavailable or the fleet reference is ambiguous. Do not treat this as no jobs.</p>}{[['Parts requests',data.tickets,'/tickets/'],['Workshop',data.incidents,'/incidents/']].map(([title,rows,prefix])=><section key={String(title)}><h3>{String(title)}</h3>{(rows as Job[]).length?(rows as Job[]).map(t=><Link className="asset-record" key={t.id} href={`${prefix}${t.id}`}><strong>{t.job_number||'Job'} · {t.status}</strong><span>{t.request_summary||t.description}</span><small>{date(t.created_at)}</small></Link>):<p>No accessible records returned.</p>}</section>)}</>}
 {tab==='faults'&&(!m?<p>This asset has no linked tracking feed.</p>:faultError||faults?.faultError?<p role="alert">{faultError||'Fault check unavailable. Missing data is not an all-clear.'}</p>:faults?<FaultCards machine={m} faults={faults.faults} checkedAt={faults.checkedAt}/>:<p role="status">Checking fault records…</p>)}
 {tab==='movements'&&<><h2>Recorded movement history</h2><label>History period <select value={days} onChange={e=>{setDays(e.target.value);setPoints(null);setMoveError('');}}><option value="1">24 hours</option><option value="7">7 days</option><option value="30">30 days</option></select></label><p>Recorded positions only. Connecting lines show displacement, not the driven route or proof of working time. Gaps over two hours are not connected.</p>{moveError?<p role="alert">{moveError}</p>:points===null?<p role="status">Loading movement history…</p>:<>{truncated&&<p>History is limited to the latest 5,000 saved samples. Choose a shorter period for more detail.</p>}{points.length?<><HistoryMap points={points}/><ol className="asset-timeline">{points.map(p=><li key={p.at}><strong>{date(p.at)}</strong><span>{p.latitude.toFixed(5)}, {p.longitude.toFixed(5)}{p.gapBefore?' · GPS gap before this report':p.metresFromPrevious!==null?` · ${p.metresFromPrevious} m from previous report`:''}</span></li>)}</ol></>:<p>No recorded GPS history in this period. Older trips cannot be reconstructed from the latest position alone.</p>}</>}</>}
 </section>;
}
