'use client';
import {OpenPartsRequests} from './open-parts-requests';
import {useEffect,useMemo,useState} from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {getSupabaseAccessToken} from '@/lib/supabase';
import {machineKey,machineBrand,partsRequestUrl} from '@/lib/integrations/jcb/types';
import {csvCell,hireLabel,type OperationRow} from '@/lib/fleet-operations/report';
import {OperationsHealth} from './health';
import './style.css';
const FleetMap=dynamic(()=>import('@/components/jcb/livelink-map'),{ssr:false,loading:()=> <p>Loading fleet map…</p>});
const label=(s:string)=>s==='on_hire'?'On hire':s==='off_hire'?'Off hire':'Location unavailable';
const n=(v:number|null|undefined,d=1)=>v===null||v===undefined?'—':v.toLocaleString('en-GB',{maximumFractionDigits:d});
const date=(v:string|null|undefined)=>v?new Date(v).toLocaleString('en-GB',{timeZone:'Europe/London'}):'Not reported';
type Run={provider:string;checked_at:string|null;checked?:number;total?:number;failures?:number;next_pin?:string|null};
type Data={rows:OperationRow[];total:number;next:string|null;from:string;to:string;cycleEndsAt:string;launchAt:string;runs:Run[];excludedConflicts:number;error?:string};
export function OperationsWorkspace(){
 const [elapsed,setElapsed]=useState(0);
 const [collecting,setCollecting]=useState(false),[collectionMessage,setCollectionMessage]=useState('');
 const [rows,setRows]=useState<OperationRow[]>([]),[meta,setMeta]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[version,setVersion]=useState(0),[days,setDays]=useState('1');
 const [focusYard,setFocusYard]=useState(true),[mapRevision,setMapRevision]=useState(0);
 const [tab,setTab]=useState('operations'),[filter,setFilter]=useState('all'),[provider,setProvider]=useState('all'),[search,setSearch]=useState(''),[price,setPrice]=useState(''),[selected,setSelected]=useState<string|null>(null);
 useEffect(()=>{if(!loading)return;const started=Date.now();setElapsed(0);const timer=setInterval(()=>setElapsed(Math.floor((Date.now()-started)/1000)),1000);return()=>clearInterval(timer);},[loading,version,days]);
 useEffect(()=>{const controller=new AbortController();setRows([]);setMeta(null);setLoading(true);setError('');
  void (async()=>{try{const token=await getSupabaseAccessToken();if(!token)throw new Error('Sign in to view Fleet Operations.');let after:string|null=null,to:string|null=null;
   do{const params=new URLSearchParams({days});if(after)params.set('after',after);if(to)params.set('to',to);const response=await fetch(`/api/fleet/operations?${params}`,{headers:{Authorization:`Bearer ${token}`},signal:controller.signal});const data:Data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to load Fleet Operations.');if(controller.signal.aborted)return;setRows(previous=>[...previous,...data.rows]);setMeta(data);after=data.next;to=data.to;}while(after);
  }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Unable to load report.');}finally{if(!controller.signal.aborted)setLoading(false);}})();return()=>controller.abort();
 },[days,version]);
 const visible=useMemo(()=>rows.filter(r=>(filter==='all'||r.hire.status===filter||r.hire.state===filter)&&(provider==='all'||(r.machine.source??'jcb')===provider)&&`${r.machine.relay?.machine_number} ${r.machine.model} ${r.machine.pin}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(a.machine.relay?.machine_number??'').localeCompare(b.machine.relay?.machine_number??'',undefined,{numeric:true})),[rows,filter,provider,search]);
 const fuelPrice=price.trim()&&Number.isFinite(Number(price))&&Number(price)>=0?Number(price):null;
 const total=(key:'fuelLitres'|'engineHours'|'idleHours'|'yardFuel'|'onHireFuel'|'unattributedFuel'|'timingEstimatedFuel'|'statusEstimatedFuel')=>{const values=visible.map(r=>r.report[key]).filter((v):v is number=>v!==null);return values.length?values.reduce((a,b)=>a+b,0):null;};
 const fuel=total('fuelLitres'),hours=total('engineHours'),idle=total('idleHours'),coverage=visible.filter(r=>r.report.fuelLitres!==null).length;
 const historyStarted=rows.map(r=>r.report.firstObserved).filter((v):v is string=>!!v).sort()[0];
 const attributionReasons=[['missingStart','No GPS near the opening fuel reading'],['missingEnd','No GPS near the closing fuel reading'],['gpsGap','Long gaps between GPS reports'],['invalidPosition','Invalid GPS or near the yard boundary'],['crossing','Observed yard crossing']] as const;
 const selectedRow=rows.find(r=>machineKey(r.machine)===selected);
 async function collectLatest(){setCollecting(true);setCollectionMessage('Collecting fresh provider readings…');try{const token=await getSupabaseAccessToken();if(!token)throw new Error('Sign in to collect readings.');const results=await Promise.allSettled(['jcb','trackunit','takeuchi'].map(async provider=>{const response=await fetch('/api/fleet/operations/collect',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({provider})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Collection failed.');return `${provider==='takeuchi'?'Takeuchi':provider==='jcb'?'JCB':'Manitou'}: ${data.recent?'already collected within 15 minutes':`${data.checked}/${data.total} checked, ${data.failures} failures`}`;}));setCollectionMessage(results.map(r=>r.status==='fulfilled'?r.value:r.reason instanceof Error?r.reason.message:'Collection failed').join(' · '));setVersion(v=>v+1);}catch(e){setCollectionMessage(e instanceof Error?e.message:'Collection failed.');setVersion(v=>v+1);}finally{setCollecting(false);}}
 function exportCsv(){const headers=['Machine','Make','Model','Location-based status','Position time','Period from','Period to','Fuel L','Engine hours','Idle hours','Aligned L/engine hour','Aligned idle %','Estimated fuel cost GBP','Fuel price GBP/L','Fuel coverage hours','Open parts requests','Yard fuel L','On-hire fuel L','Fuel needing location attention L','GPS timing estimate L','Last-known status estimate L'];const csv=[headers,...visible.map(r=>[r.machine.relay?.machine_number,machineBrand(r.machine),r.machine.model,hireLabel(r.hire),r.hire.position?.at,meta?.from,meta?.to,r.report.fuelLitres,r.report.engineHours,r.report.idleHours,r.report.litresPerHour,r.report.idlePercent,fuelPrice!==null&&r.report.fuelLitres!==null?r.report.fuelLitres*fuelPrice:null,fuelPrice,r.report.fuelCoverageHours,r.openPartsRequests?.length??null,r.report.yardFuel,r.report.onHireFuel,r.report.unattributedFuel,r.report.timingEstimatedFuel,r.report.statusEstimatedFuel])].map(row=>row.map(csvCell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`relay-fleet-operations-${meta?.to.slice(0,10)||'report'}.csv`;a.click();URL.revokeObjectURL(url);}
 return <div className="fo-workspace"><header className="fo-heading"><div><span className="fo-eyebrow">MLP · JCB + MANITOU + TAKEUCHI</span><h1>Fleet Operations</h1><p>Fuel, operating hours, location and machine health.</p></div><div className="fo-actions"><Link href="/fleet">Fleet register</Link><button disabled={loading||collecting} onClick={()=>setVersion(v=>v+1)}>Refresh</button><button disabled={collecting||loading} onClick={()=>void collectLatest()}>{collecting?"Collecting…":"Collect latest readings"}</button><button disabled={loading||!!error||!rows.length} onClick={exportCsv}>Export CSV</button><button onClick={()=>window.print()}>Print / PDF</button></div></header>
 <nav className="fo-tabs" aria-label="Fleet Operations views">{[['operations','Operations'],['yard','Yard geofence'],['health','Fleet Health & Error Codes']].map(([id,title])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{title}</button>)}</nav>
 {error&&<p role="alert" className="fo-error">{error} Report incomplete; totals must not be treated as the whole fleet.</p>}
 {collectionMessage&&<p role="status">{collectionMessage}</p>}
 <p className="fo-coverage" role="status">{loading?`Loading report · ${elapsed}s elapsed · `:error?'Report incomplete · ':'Report loaded · '}{rows.length} / {meta?.total??'—'} active tracked MLP machines · {meta?`${date(meta.from)} – ${date(meta.to)}`:'Waiting for reporting history'}</p>
 {loading&&<><progress aria-label="Fleet report loading" max={meta?.total||1} value={rows.length}/><p>Loading machine history. Totals are incomplete until this finishes; GPS update status is separate.</p></>}
 <p className="fo-coverage">Automatic collection hourly: JCB at 5 minutes past, Manitou at 35 minutes past, Takeuchi at 45 minutes past. Refresh reloads saved readings; Collect latest readings checks providers, at most once per 15 minutes. A machine’s GPS timestamp changes only when its tracker reports.</p>
 {meta?.runs.map(run=><p className="fo-collection" key={run.provider}>{run.provider==='takeuchi'?'Takeuchi':run.provider==='jcb'?'JCB':'Manitou'} collection: {date(run.checked_at)}{run.checked_at?` · ${run.checked}/${run.total} checked · ${run.failures??0} failures${run.next_pin?' · continuing next scheduled run':''}${Date.now()-Date.parse(run.checked_at)>2*3600000?' · overdue':''}`:' · awaiting first collection'}</p>)}
 {!!meta?.excludedConflicts&&<p className="fo-error">{meta.excludedConflicts} duplicate tracking identities excluded to prevent double-counting. Review machine links.</p>}
 {tab==='health'?(!loading&&!error?<OperationsHealth machines={rows} initialSearch={selectedRow?.machine.relay?.machine_number}/>:<p>Finish loading the fleet before checking error codes.</p>):<>
 <div className="fo-controls"><label>Reporting period<select value={days} onChange={e=>setDays(e.target.value)}><option value="1">Today · midnight UK</option><option value="7">7 calendar days · UK</option><option value="30">30 calendar days · UK</option></select></label><label>Location-based hire status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All machines</option><option value="on_hire">On hire</option><option value="off_hire">Off hire</option><option value="unknown">All location issues</option><option value="stale">Not checked in (over 24h)</option><option value="missing">No GPS location</option><option value="invalid">Invalid GPS</option><option value="boundary">Near yard boundary</option><option value="crossing">Awaiting crossing update</option></select></label><label>Manufacturer<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="all">JCB + Manitou + Takeuchi</option><option value="jcb">JCB</option><option value="trackunit">Manitou</option><option value="takeuchi">Takeuchi</option></select></label><label>Find machine<input placeholder="Fleet number, model or PIN" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Fuel price (£ / litre)<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Enter price for estimate"/></label></div>
 <div className="fo-metrics">{[[`${visible.filter(r=>r.hire.status==='on_hire').length}`,'On hire','Outside Garboldisham yard'],[`${visible.filter(r=>r.hire.status==='off_hire').length}`,'Off hire','Inside the yard'],[`${visible.filter(r=>r.hire.status==='unknown').length}`,'Location needs attention',`${visible.filter(r=>r.hire.state==='stale').length} not checked in · ${visible.filter(r=>['missing','invalid'].includes(r.hire.state)).length} missing/invalid · ${visible.filter(r=>r.hire.state==='boundary').length} near boundary · ${visible.filter(r=>r.hire.state==='crossing').length} awaiting crossing update`],[`${n(fuel)} L`,'Fuel consumed',`${coverage}/${visible.length} machines with counter intervals`],[`${n(hours)} h`,'Engine running',`${n(idle)} h idle reported`],[fuel!==null&&fuelPrice!==null?`£${n(fuel*fuelPrice,2)}`:'—','Estimated fuel cost',fuelPrice===null?'Enter your fuel price':'Recorded litres × entered price']].map(([value,title,detail])=><article key={title}><span>{title}</span><strong>{loading?'…':value}</strong><small>{loading?'Loading fleet totals…':detail}</small></article>)}</div>
 {tab==='yard'?<><div className="fo-section-heading"><div><h2>Garboldisham yard</h2><p>Millpond Farm, Thetford Road, Garboldisham, IP22 2SP</p></div><a href="https://www.openstreetmap.org/way/209973226" target="_blank" rel="noreferrer">Boundary source</a></div><p>Inside = off hire. Outside = on hire. The first valid location sets hire status immediately. A change across the yard boundary needs two distinct GPS reports. Pins with GPS over 24 hours old are marked “Not checked in” at their last known position. Missing GPS and positions within 20 metres of the boundary are labelled separately. This does not change hire contracts or billing.</p><div className="fo-actions"><button aria-pressed={focusYard} onClick={()=>{setSelected(null);setFocusYard(true);setMapRevision(v=>v+1);}}>Focus yard</button><button aria-pressed={!focusYard} onClick={()=>{setSelected(null);setFocusYard(false);setMapRevision(v=>v+1);}}>Show whole fleet</button></div><FleetMap key={mapRevision} machines={visible.map(r=>r.machine)} selectedPin={selected} onSelect={setSelected} showYard focusYard={focusYard}/></>:<>
 <div className="fo-analysis"><section><h2>Fuel by yard / on-hire status</h2>{[['Yard',total('yardFuel')],['On hire',total('onHireFuel')],...(total('unattributedFuel')?[['Needs location attention',total('unattributedFuel')]]:[])].map(([name,value])=><div className="fo-bar-row" key={String(name)}><span>{name}</span><meter aria-label={`${name} fuel litres`} min="0" max={fuel||1} value={typeof value==='number'?value:0}/><strong>{n(value as number|null)} L</strong></div>)}<p>Fuel consumption is measured. Yard/on-hire allocations include estimates. {n(total('timingEstimatedFuel'))} L uses GPS within 15 minutes of the fuel-reading times. {n(total('statusEstimatedFuel'))} L is allocated using the machine’s last known valid status where historical GPS is incomplete, including crossings. This is an estimate, not proof of where fuel was used.</p>{!!total('unattributedFuel')&&<details className="fo-attribution"><summary>Machines needing location attention</summary><ul>{attributionReasons.map(([key,title])=>{const litres=visible.reduce((sum,r)=>sum+(r.report.unattributedReasons?.[key]??0),0);return litres>0?<li key={key}>{title}: <strong>{n(litres)} L</strong></li>:null;})}</ul><p>These machines have no valid location available for an estimate. Their fuel remains included in the total.</p></details>}</section><section><h2>Reporting coverage</h2><p><strong>{coverage} of {visible.length}</strong> machines have measured fuel changes in this period.</p><p>Daily reporting starts at midnight UK time. {meta&&<>This cycle closes {date(meta.cycleEndsAt)} UK. Reporting began {date(meta.launchAt)} UK.</>} The current cycle is partial until it closes. Clock-change days follow UK midnight boundaries.</p><p>Saved history starts {date(historyStarted)}. A dash means insufficient data. Long gaps and meter resets are excluded; available intervals may cover only part of the selected period.</p><p>Idle percentages and fuel efficiency use readings covering the same intervals. Non-idle time is not a measure of productive output.</p></section></div>
 <h2>Machine operations</h2><div className="fo-table-scroll"><table><thead><tr>{['Machine','Hire status','Fuel used','Engine / idle','L / engine h','Idle %','Fuel coverage','Details'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={machineKey(r.machine)} className={r.openPartsRequests?.length?'fo-has-request':undefined}><td><strong>{r.machine.relay?.machine_number}</strong><small>{machineBrand(r.machine)} {r.machine.model}</small><OpenPartsRequests requests={r.openPartsRequests}/></td><td><span className={`fo-status fo-${r.hire.status}`}>{hireLabel(r.hire)}</span><small>{r.hire.reason}</small><small>GPS: {date(r.hire.position?.at)}{r.hire.position?.at&&meta?` · ${n(Math.max(0,(Date.parse(meta.to)-Date.parse(r.hire.position.at))/3600000))} h old`:""}</small></td><td>{n(r.report.fuelLitres)} L{r.report.statusEstimatedFuel>0&&<small>{n(r.report.statusEstimatedFuel)} L location estimated from last known status</small>}{r.report.unattributedFuel!==null&&r.report.unattributedFuel>0&&<small>Needs location attention</small>}</td><td>{n(r.report.engineHours)} / {n(r.report.idleHours)} h</td><td>{n(r.report.litresPerHour)}</td><td>{n(r.report.idlePercent)}%</td><td>{n(r.report.fuelCoverageHours)} h</td><td><button onClick={()=>setSelected(machineKey(r.machine))}>View machine</button></td></tr>)}</tbody></table></div>
 {!visible.length&&!loading&&<p>No tracked MLP machines match this view. New reporting history appears after collection.</p>}
 </>}
 {selectedRow&&<section className="fo-detail" aria-label="Selected machine"><div className="fo-section-heading"><h2>{selectedRow.machine.relay?.machine_number} · {machineBrand(selectedRow.machine)} {selectedRow.machine.model}</h2><button onClick={()=>setSelected(null)}>Close details</button></div><OpenPartsRequests requests={selectedRow.openPartsRequests}/><p>{hireLabel(selectedRow.hire)} · {selectedRow.hire.reason}</p>{selectedRow.report.statusEstimatedFuel>0&&<p><strong>{n(selectedRow.report.statusEstimatedFuel)} L allocated by last known status — estimated.</strong></p>}<p>GPS reported: {date(selectedRow.hire.position?.at)} · Last confirmed: {label(selectedRow.hire.lastKnown)} {date(selectedRow.hire.lastKnownAt)}</p><div className="fo-detail-values"><p><strong>{n(selectedRow.machine.fuel?.value)}%</strong> fuel remaining<small>{date(selectedRow.machine.fuel?.at)}</small></p><p><strong>{n(selectedRow.machine.hours?.value)} h</strong> lifetime engine hours<small>{date(selectedRow.machine.hours?.at)}</small></p><p><strong>{n(selectedRow.machine.fuelUsed24h?.value)} L</strong> provider rolling 24h fuel<small>{date(selectedRow.machine.fuelUsed24h?.at)} · separate from period totals</small></p></div><div className="fo-actions"><button onClick={()=>setTab('health')}>View fleet error codes</button>{partsRequestUrl(selectedRow.machine)&&<Link href={partsRequestUrl(selectedRow.machine)!}>Raise parts request</Link>}<Link href={selectedRow.machine.source==='takeuchi'?'/takeuchi':selectedRow.machine.source==='trackunit'?'/manitou':'/livelink'}>Open tracking view</Link></div></section>}
 </>}
 </div>;
}
