'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';
import {assetRequest} from '@/components/assets/request';
import {mayAct,workflowLabels,type HireAssessment,type WorkflowAccess} from '@/lib/fleet-workflow/model';
import './style.css';
import {HoldReasons} from './hold-reasons';
import {WorkflowAccess as WorkflowAccessSettings} from './access';
type Message={id:string;machine_id:string;team:string;title:string;detail:string;severity:string;read:boolean;created_at:string};
type Data={rows:HireAssessment[];access:WorkflowAccess;messages:Message[];audit:{id:string;action:string;reason:string;created_at:string;actor_id:string}[];truncated:boolean};
const actions=[['workshop_clear','Record workshop inspection'],['parts_clear','Confirm parts check'],['service_complete','Record completed service'],['service_plan','Set next service due'],['release','Clear and make available'],['override','Override for hire'],['hold','Put on hold']] as const;
export function FleetWorkflow(){
 const [data,setData]=useState<Data|null>(null),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[selected,setSelected]=useState<string|null>(null),[version,setVersion]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[action,setAction]=useState(''),[submission,setSubmission]=useState<string|null>(null),[message,setMessage]=useState('');
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');void assetRequest<Data>('/api/fleet/workflow?'+new URLSearchParams(selected?{machine:selected}:{q:search}),abort.signal).then(d=>{if(!abort.signal.aborted)setData(d)}).catch(e=>{if(!abort.signal.aborted){setError(e.message);setData(null)}}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[search,selected,version]);
 const row=selected?data?.rows.find(r=>r.machine_id===selected):null;
 async function read(id:string){try{await assetRequest('/api/fleet/workflow',undefined,{action:'read',id});setVersion(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Unable to update inbox')}}
 return <section className="hire-workflow"><header><div><h1>Return to hire</h1><p>Yard arrival → workshop & parts checks → clearance → dispatch.</p></div><Link href="/fleet/map">Fleet map</Link><button disabled={loading||busy} onClick={()=>setVersion(v=>v+1)}>Refresh</button></header>
 <p>Being in the yard does not mean ready for hire. Green clearance requires recorded checks, a service schedule and no outstanding blockers. Overrides retain their warning and audit record.</p>
 <form className="workflow-search" onSubmit={e=>{e.preventDefault();setSelected(null);setAction('');setSearch(query)}}><label>Fleet number<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search machine"/></label><button disabled={busy}>Search</button></form>
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{loading&&<p role="status">Checking clearance…</p>}
 {data&&!loading&&<>{data.access.admin&&<WorkflowAccessSettings/>}<div className="workflow-grid"><section><h2>{row?'Machine clearance':search?'Search results':'Yard return queue'}</h2>{selected&&<button onClick={()=>{setSelected(null);setAction('')}}>← Back to queue</button>}{data.truncated&&<p>First 100 machines shown. Search a fleet number to narrow the list.</p>}{!data.rows.length&&<p>No matching machines in this queue. Search a fleet number to open its workflow.</p>}
 {data.rows.map(r=><article key={r.machine_id} className={'workflow-card '+(r.status==='available'?'clear':r.available?'override':'hold')}><h3>{r.machine_number??r.machine_id} · {r.model??'Machine'}</h3><strong>{workflowLabels[r.status]??r.status}</strong>{r.state?.departure_status&&<p>Last departure: {r.state.departure_status==='green'?'✓ Cleared':r.state.departure_status==='override'?'Authorised override':'⚠ Left without clearance'}</p>}<HoldReasons row={r}/>{r.state?.override_reason&&<p>Override reason: {r.state.override_reason}</p>}{(r.state?.next_service_date||r.state?.next_service_hours!=null)&&<p>Next service: {r.state?.next_service_date??'no date set'}{r.state?.next_service_hours!=null?` · ${r.state.next_service_hours} h`:''}</p>}<div className="workflow-buttons"><button onClick={()=>{setSelected(r.machine_id);setAction('')}}>Open workflow & history</button><Link href={`/assets/${r.machine_id}`}>Machine record</Link><Link href="/incidents">Workshop jobs</Link><Link href={`/submit?machineReference=${encodeURIComponent(r.machine_number??'')}&asset=${r.machine_id}`}>Raise parts request</Link></div>
 {row&&<><div className="workflow-buttons">{actions.filter(([key])=>mayAct(data.access,key)).map(([key,label])=><button key={key} disabled={busy} onClick={()=>{setAction(key);setSubmission(crypto.randomUUID());setMessage('')}}>{label}</button>)}</div>{action&&<form className="workflow-action" onSubmit={async e=>{e.preventDefault();if(!submission)return;const f=new FormData(e.currentTarget),payload:Record<string,string|number>={};for(const k of ['next_service_date','next_service_hours','completed_hours']){const value=f.get(k);if(typeof value==='string'&&value)payload[k]=k==='next_service_date'?value:Number(value)}setBusy(true);setError('');try{await assetRequest('/api/fleet/workflow',undefined,{id:submission,machineId:r.machine_id,version:r.version,action,reason:f.get('reason'),payload});setAction('');setMessage('Recorded. Workshop, parts and hire inboxes updated.');setVersion(v=>v+1)}catch(err){setError(err instanceof Error?err.message:'Unable to save')}finally{setBusy(false)}}}><h3>{actions.find(a=>a[0]===action)?.[1]}</h3>{action==='override'&&<p>Authorises hire despite the listed blockers. It does not record repairs or clear faults. A new blocker or return cycle invalidates this override.</p>}<label>Work completed / decision and reason<textarea name="reason" required minLength={5} maxLength={1500} disabled={busy}/></label>{['service_plan','service_complete'].includes(action)&&<><label>Next service date<input type="date" name="next_service_date" disabled={busy}/></label><label>Next service at engine hours<input type="number" min="0" step="0.1" name="next_service_hours" disabled={busy}/></label><p>Record at least one next-due threshold from the machine service plan.</p>{action==='service_complete'&&<label>Hours at completion<input type="number" required min="0" step="0.1" name="completed_hours" disabled={busy}/></label>}</>}<button disabled={busy} type="submit">{busy?'Saving…':'Record decision'}</button><button type="button" disabled={busy} onClick={()=>setAction('')}>Cancel</button></form>}</>}
 </article>)}{row&&<section><h2>Audit history</h2>{data.audit.map(a=><article key={a.id}><strong>{a.action}</strong><p>{a.reason}</p><small>{new Date(a.created_at).toLocaleString('en-GB')} · Actor {a.actor_id}</small></article>)}</section>}</section>
 <aside><h2>Workshop / parts / hire inbox</h2><p>No pop-up notifications. Each authorised team sees its own messages.</p>{!data.messages.length&&<p>No workflow messages yet.</p>}{data.messages.map(m=><article className={'workflow-card '+m.severity} key={m.id}><small>{m.team.toUpperCase()} · {new Date(m.created_at).toLocaleString('en-GB')}</small><h3>{m.title}</h3><details><summary>View checks and warnings</summary><p>{m.detail}</p></details><button onClick={()=>{setSelected(m.machine_id);setAction('')}}>Open machine</button>{!m.read&&<button onClick={()=>read(m.id)}>Mark read</button>}</article>)}</aside></div></>}
 </section>;
}
